### ISSUE TITLE
Glow node

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#100]
hello

Glow is needed effect, then not soon, in next time ok?
glow is missed from natron..
i find command of imagemagick:
http://fmwconcepts.com/imagemagick/glow/index.php

this is memo note.

**Comment by olear** [comment]
did a glow plugin in 2014 in the openfx-magic bundle, don't remember the status.

**Comment by manuelsongokuh** [comment]
yes i did see openfx-magic but it is off link, "not found"..
so i write here for you ok?

**Comment by sozap** [comment]
hello,
I don't see this as a top priority because it's already doable with a node group.
IMO it's better to concentrate on features that are impossible to do otherwise and can have various applications. Then these nodes can be combined in nodegroups for more complicated and specific effects.

**Comment by manuelsongokuh** [comment]
yes, as i said: "not soon" and "next time" this mean dont know WHEN..ok?

**Comment by rcspam** [comment]
[Francois CoyHot Grassard](https://www.facebook.com/francois.grassard) has made some plugins including a blow : http://www.coyhot.com/no_CoyHot/Natron/PyPlugs/
Try it if this is what you want to get ;)

**Comment by olear** [comment]
cool, we need more community plugins/macros :)

**Comment by olear** [comment]
already several alternatives, closing.
