### ISSUE TITLE
Texture: add params for custom from-to colors

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#101]
Add support for custom params from-to colors.

**Comment by manuelsongokuh** [comment]
also for gradient custom rom to colors ok?
also as #70 ![image](https://cloud.githubusercontent.com/assets/12126929/8006443/36672084-0b94-11e5-92a9-30096d28fe0e.jpg)

ok?

**Comment by olear** [comment]
from and to will be empty fields, input what's support by ImageMagick :) (name, hex etc)

**Comment by manuelsongokuh** [comment]
of course for input! but can be "picker color" ?
see example
https://www.google.it/search?q=picker+color&safe=off&biw=1650&bih=924&tbm=isch&tbo=u&source=univ&sa=X&ei=nbeKVcexPKv6ygPXk6hQ&ved=0CD4QsAQ

**Comment by olear** [comment]
a regular color picker or just an empty custom field? (or both)

**Comment by manuelsongokuh** [comment]
maybe..both.. ...if you find difficolt then to use picker (that is sure to need it).. 
okay?

**Comment by olear** [comment]
Will add custom fields first, then see if color picker works ok.

**Comment by olear** [comment]
added custom params in trunk, may add color picker later ...

**Comment by manuelsongokuh** [comment]
OK, that is fine for you ok?
feel you later
