### ISSUE TITLE
ReadPSD: OCIO colorspace on layers (multi-plane)

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#106]
Add PSD reader

**Comment by olear** [comment]
added in trunk

**Comment by devernay** [comment]
You could also have one plugin to read all the available layers, using the multiplane suite (see ReadOIIO), but I guess it wouldn't make that much of a difference performance-wise.

**Comment by olear** [comment]
will look into, just started with the read stuff :)

**Comment by manuelsongokuh** [comment]
GOOO   GOOOO   GOOO!!!

**Comment by olear** [comment]
@devernay What's the option/possibility for multiple outputs (one dstclip for each layer)? Couldn't find any examples.

**Comment by devernay** [comment]
look for "MultiPlanar" "Plane" "ComponentsPresent" in ofxsImageEffect.h and ReadOIIO.cpp

there is also doc in fnOfxExtension.h

basically, if the host is multiplanar, you effect should tell the host it is multiplanar, and implement the getClipComponents virtual function. The plane to render is passed as an argument to the render action.

**Comment by olear** [comment]
Maybe a stupid question, but how do I access more than one image from ReadOIIO?
![screenshot-18](https://cloud.githubusercontent.com/assets/7461595/8283325/fd5e521a-18f6-11e5-8fd3-2fb4df4ca5bf.png)
I see no extra outputs, just the possibility to switch channel/layer on the single output.

**Comment by devernay** [comment]
If it's a multilayer image, then all layers will be available downstream (for example to shuffle nodes)

**Comment by olear** [comment]
Ahh, my bad, misunderstood. Will probably add feature this weekend.

**Comment by olear** [comment]
So in the decodePlane function I just get values from the channels params and comp an image based on that (four images) and write back the comp, or just one channel?

Each channel param should contain(?):
```
0
1
R
G
B
A
layer_1.R
layer_1.G
layer_1.B
layer_1.A
layer_2.R
layer_2.G
layer_2.B
layer_2.A
...
```

**Comment by olear** [comment]
sorry for the dumb questions, found out :)

**Comment by olear** [comment]
Ok, got initial support for muliplane, but still got some problems with layer offset, and it looks like the layers don't get applied colorspace ....

Original in Gimp:
![screenshot-2](https://cloud.githubusercontent.com/assets/7461595/8390712/c6234a20-1ca3-11e5-82e1-23c949ab7e90.png)
Result:
![screenshot-4](https://cloud.githubusercontent.com/assets/7461595/8390713/cbbffb90-1ca3-11e5-9a0c-a46914e68c47.png)
As you can see in view2 the 2 last layers don't stack as they should when I combine layers, and the layers have wrong color compared to view1.
![screenshot-3](https://cloud.githubusercontent.com/assets/7461595/8390714/d187a8a2-1ca3-11e5-89d2-8145847b8692.png)

**Comment by devernay** [comment]
there is a bug, colorspace transform is only applied to the main color plane
--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by olear** [comment]
Multiplane seems to work, tested with several images, and I get access to layers through other nodes. Also compared general result to what Nuke does, and they are pretty equal (actually psd's from gimp work better in ReadPSD than in Nuke).

**Comment by MrKepzie** [comment]
the thing is how do we decide which plane get the CS correction? Do we look for RGB channel names? We cannot apply correction on depth, XYZ (etc...) planes

**Comment by MrKepzie** [comment]
I fixed it in openfx-io

**Comment by olear** [comment]
Latest commit gives me render error:
![screenshot-6](https://cloud.githubusercontent.com/assets/7461595/8391439/33b1cb00-1cc4-11e5-8df2-576e642d0a8e.png)
Before last commit:
![screenshot-7](https://cloud.githubusercontent.com/assets/7461595/8391442/3a0f1dc2-1cc4-11e5-9cee-a374ee66f29f.png)

**Comment by MrKepzie** [comment]
The error is in the render action of your plug-in, set a break point to see which exception is thrown

**Comment by olear** [comment]
Caught exception: OCIO: invalid components (only RGB and RGBA are supported)

**Comment by MrKepzie** [comment]
if you support multiple you need to also support ePixelCOmponentNone

**Comment by olear** [comment]
Don't quite understand ... I output RGBA-only.

**Comment by olear** [comment]
Still unsure what I need to do to get this to work...

**Comment by MrKepzie** [comment]
Apparently my previous email got evicted. 

When Natron requests a custom plane (= layer) and if your plug-in is flagged as supporting multi-plane ( setIsMultiPlanar(multiPlanar);) it will pass ePixelComponentsNone. You have to figure out the plane name requested by using the OFX::mapPixelComponentCustomToLayerChannels function on the "raw" components string (like done in GenericReader). 
Generally I think in PSD the layers can only be RGB(A?) so you only have to support 3/4-component planes. But for ReadOIIO we had to also support 2-component planes (such as X/Y motion vectors).

**Comment by olear** [comment]
the layer stuff works as it should (you request a layer using merge etc and you get that layer), my problem is https://github.com/MrKepzie/openfx-io/commit/5a98decc3b5e056ffec7c3abdef29a848e728fe2, this commit breaks that, or I need to adapt to something?

Sorry if I misunderstand something (I often do :) )

**Comment by olear** [comment]
Current workaround is to stay at https://github.com/MrKepzie/openfx-io/commit/b1bf4d466f9a2acc215ac5a39f68bfcbd7c2ca46 and use a OCIOColorSpace node after the layer.

**Comment by MrKepzie** [comment]
What's the problem? The commit you point to just checks for the existence of R,G,B channels (it must be explicitly called "R" "G" "B" in the layer). If it finds it, then it checks OCIO for colorspace conversion, otherwise it just skips it. I suspect your layers do not have channels named "R" "G" "B" thus always falling into the "other plane type" case (i.e: no colorspace conversion)

**Comment by olear** [comment]
```
NatronOfxImageComponentsPlane_Layer #2_Channel_R_Channel_G_Channel_B_Channel_A
```
```
std::cout << layerChannels[0] << layerChannels[1] << layerChannels[2] << layerChannels[3] << layerChannels[4] << std::endl;
```
```
Layer #2RGBA
```

**Comment by MrKepzie** [comment]
It works fine here, I'm guessing you are not using the Shuffle/Merge node properly, on my end everything works fine.

**Comment by olear** [comment]
hmm, I just add a merge, put the readpsd on A and select the channel.

**Comment by MrKepzie** [comment]
Oh yeah. You did not upgrade the openfx-io submodule version, with the fix I made for colorspace it works fine here

**Comment by olear** [comment]
That's because it didn't work here... Will test when I get home (~2 hours).

**Comment by MrKepzie** [comment]
I’ve pushed a few fixes for colorspaces/premultiplication, it is now fixed for good in openfx-io
