### ISSUE TITLE
Update Windows(MinGW) depends

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#109]
This is most likely going to be a dependency hell ...

Need to get Pango + librsvg up and going.

the Pango stuff in deploy.sh should work in theory, but last time I tested it I think it failed at libffi (the first depend :P ).

Also remember that Pango, glib, and librsvg is LGPL, so they must be dll's

**Comment by olear** [comment]
Don't forget libxml2 and OCIO (+cmake)....

**Comment by devernay** [comment]
why LGPL = DLL? I don't see anything about that anywhere in the license. You can link statically to LGPL libraries, the only thing is that you have to distribute the licence with it.
GPL libraries are another problem (you can't distribute them with non-GPL binaries, they have to be distributed separately)

**Comment by olear** [comment]
I though that if I linked against static LGPL libs, then I would get problems related to the BSD license, but I may be mistaken, I have always used shared LGPL just to be safe.

If I can avoid dll's then great :)

**Comment by devernay** [comment]
there's no problem for statically linking LGPL libraries with *open source* BSD-licensed code. 
from http://www.gnu.org/copyleft/lesser.html :

d) Do one of the following:

    0) Convey the Minimal Corresponding Source under the terms of this License, and the Corresponding Application Code in a form suitable for, and under terms that permit, the user to recombine or relink the Application with a modified version of the Linked Version to produce a modified Combined Work, in the manner specified by section 6 of the GNU GPL for conveying Corresponding Source.
    1) Use a suitable shared library mechanism for linking with the Library. A suitable mechanism is one that (a) uses at run time a copy of the Library already present on the user's computer system, and (b) will operate properly with a modified version of the Library that is interface-compatible with the Linked Version.

If you're doing (0) (your code is open source) you don't need (1)

**Comment by olear** [comment]
Thanks for the information. Will do a 100% static build on Win (if possible).

**Comment by olear** [comment]
Got problems with glib, will move to MSYS2 and see if I can avoid building a complete OS just to get the plugins working ;)

**Comment by olear** [comment]
MSYS2 got all depends, and IM builds as it should, the cons are dll's and probably a lot of bloated depends. One possibility is to modify the PKGBUILD's and force static and remove bloated depends and rebuild, or continue on MSYS(1) and try to get glib building etc.Pros: all depends are installed using one command.

**Comment by olear** [comment]
Current depends with MSYS2:
```
libOpenColorIO.dll
libbz2-1.dll
libcairo-2.dll
libcroco-0.6-3.dll
libexpat-1.dll
libffi-6.dll
libfontconfig-1.dll
libfreetype-6.dll
libgcc_s_seh-1.dll
libgdk_pixbuf-2.0-0.dll
libgio-2.0-0.dll
libglib-2.0-0.dll
libgmodule-2.0-0.dll
libgobject-2.0-0.dll
libgomp-1.dll
libharfbuzz-0.dll
libiconv-2.dll
libintl-8.dll
libpango-1.0-0.dll
libpangocairo-1.0-0.dll
libpangoft2-1.0-0.dll
libpangowin32-1.0-0.dll
libpixman-1-0.dll
libpng16-16.dll
librsvg-2-2.dll
libstdc++-6.dll
libtinyxml-0.dll
libwinpthread-1.dll
libxml2-2.dll
zlib1.dll
```
