### ISSUE TITLE
ReadSoX : get "curve" data from audio

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#110]
Make a Read node for WAV/AIFF.

milestone 1: collect data
milestone 2: create a simple waveform.
milestone 3: find a way to share data with other nodes etc.
milestone 4: And finally as a bonus some way to inform WriteFFMpeg to include that file when rendering.

libsndfile is a nice library to use.

**Comment by devernay** [comment]
IMHO ReadFFmpeg should read the audio. FFmpeg supports WAV, too, so there's no need to write anything else.

Audio handling with OpenFX is still being discussed.

What do you think of the way it is dealt with in Nuke?

I think the audio enveloppe should be displayed in the timeline and curve editor.

Should audio be decoded by ReadFFmpeg/reencoded by WriteFFmpeg, or should we avoid transcoding when possible? how?

**Comment by olear** [comment]
Understand that ffmpeg should handle it, but the issue request in Natron is very old, and I need to do something :) I want that feature as well, a simple way to get waveform params from a wav that can control params in other nodes.

I'm open to all suggestions, I'm used to the simple way it works in Shake (no experience with sound in Nuke).

Have a mockup, but I can stop of course...
![screenshot-17](https://cloud.githubusercontent.com/assets/7461595/8282592/16512310-18f2-11e5-88a8-c1c46406ede4.png)

**Comment by rcspam** [comment]
sox can create text data from an audio file.
The sox library is multiplatform.
Hope that help.

**Comment by rcspam** [comment]
Here is the Python sox librarie: https://pypi.python.org/pypi/pysox

**Comment by rcspam** [comment]
Little precision:  .dat file generate by sox are really simple:
2 infos:  Sample Rate and number of Channel;
Then n columns:  Time |  Channel 1 | Channel n ... 

e.g.:
```
; Sample Rate 48000 
; Channels 2
            0    0.00035699829   0.00035699829
2.0833333e-05    0.00028520077   0.00028520077 
4.1666667e-05    0.00022141356   0.00022141356
     6.25e-05    0.00018240418   0.00018240418
```
1 line / sample. So 47 sec at 48000 Hz  give 2256000 lines and the file grow up quickly, about in this case 115 Mo...
Cheers

**Comment by mash-graz** [comment]
i have to second the statement of devernay!

audio handling in natron should by done by help of ffmpegs de-/mux capabilities and as close related to openfx standards as possible!

an isolated ReadWav node (as in older versions of nuke) does not make much sense. it's an ugly workaround and doesn't fit very well in the data flow notation of node based compositing.
(btw: vapoursynth shows very similar shortcomings concerning audio handling)

what we really need is sound support in the main openfx import/export nodes and a transparent way to pipe it though all the processing! this should be realized in a way, that even commercial products like nuke or resolve may use as an attractive alternative to their (usually quicktime centered) audio-import mechanism.

when devernay asks: "What do you think of the way it is dealt with in Nuke?"
i have to answer: i don't know, how it is really done in nuke internal!
nuke-studio shows very well, that the old old simple ReadWav node doesn't fit very well in a future proof framework, but on the other hand it does not have any working sound support beside it's mac/windows quicktime based import up to wow! therefore all the more advanced editing functions of nuke studio are not usable on linux right now. :(

**Comment by rcspam** [comment]
Hi,
The AudioRead node in Nuke generating a simple curve. A node to do that in Natron could be cool. Even if I'm not a c/c++ devel, it must be easy to code (i hope) with sox lib (just like IM lib) can help to do that easily:
With the command line:
*$ sox -r 1 file.mp3 curve.dat*
convert simply an audio file in an ascii curve at  1 hz (-r SampleRate in hz), so if we import it in Natron in the curve editor, openfx code must do that as well.

Here detail about .dat file http://sox.sourceforge.net/soxformat.html (see .dat format)

**Comment by rcspam** [comment]
I share 100% of your [point of view](https://github.com/olear/openfx-arena/issues/110#issuecomment-114408069), but when devernay says "Audio handling with OpenFX is still being discussed", short-term ? long-term? An openfx-fork could be developped with ffmpeg sound support, could be?  For the need of Natron, it must be stay compatible with the "no-sound openfx". But pehaps this is an already dead in advance assumption !

**Comment by olear** [comment]
I'm not going to discuss pros/cons for anything here (didn't expect that much "noise").

My point of view:

I use Shake, I want to move to Natron. I often use the "ReadWav" feature in Shake, all I want is to get some params based on the Wav and then use them in another node. I don't care about actual audio support in OpenFX or in the host (I would like the feature, don't get me wrong).

I'm open to all suggestions ...

If no suggestions/solutions arrive before I'm done with 0.8 then I will create a ReadWAV node (if not just for my own use), call it what you want ....

**Comment by rcspam** [comment]
I want  a read node to read some audio files as well and to import curve from them. That is what i want !

You can see [here](https://groups.google.com/forum/?hl=en#!topic/natron-vfx/5WhYboYkSNQ)  a little script to import curve

**Comment by olear** [comment]
Thanks for the info, should at least work as a workaround :)

**Comment by olear** [comment]
Ok, new mission goal:

ReadSOX, more or less a c++ version of what @rcspam does in the bash script (may need your help on this one).

step.1: read the data needed to calculate what's needed
step.2: calculate and share the needed data with other nodes

Will concentrate on the other Read nodes first, I also need to checkout libsox (only used it on the commandline). Unsure if this will happen in v0.8 or v0.9.

**Comment by olear** [comment]
Moved to https://github.com/rcspam/audio2ascii (will help make a portable qt gui)

Then everybody is happy :) (?)

**Comment by rcspam** [comment]
Very great OOOPS, my inexperience cause "a big pull request remove" .
Can you do something ?
Very Sorry

**Comment by olear** [comment]
@devernay : a nice feature in WriteFFMpeg would be an extra field for audio, as in Nuke:
![audiow](https://cloud.githubusercontent.com/assets/7461595/8382751/4b7a55ac-1c35-11e5-91b4-9d71914bbba1.png)

**Comment by devernay** [comment]
sure, it's in the roadmap... but we are focused on the Natron 2.0 release right now.

the thing is to grab the necessary parts from ffmpeg.c

what about transcoding? My opinion is that no transcoding should be done at all, or it would add a zillion more options.

Please file an issue in openfx-io whenever you have time.
--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by olear** [comment]
No rush.

As long as ffmpeg writes audio that's compatible with the output video container there should be no issues, but simple trancoding may be needed (or does ffmpeg handle this when you embed an audio file when transcoding, don't remember).

**Comment by olear** [comment]
Still would like a ReadSoX plugin ... Add when I get the time (low pri).
