### ISSUE TITLE
feedback [OpenFX-Arena 0.8Beta1]

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#111]
i have CRASH when i add Pango..
natron 22cef47ae4154483ba0061b8c8f8f7732be8fdad

**Comment by manuelsongokuh** [comment]
![schermata9](https://cloud.githubusercontent.com/assets/12126929/8288010/c2e2f8d0-1913-11e5-9c93-630794f55f31.png)

**Comment by olear** [comment]
Known issue in Natron, some renderscale issue. This affects Texture and TextPango. Downgrade to Natron1 or wait for an build that fixes the problem.

**Comment by olear** [comment]
Can provide alternative binaries on next arena build that have renderscale enabled to avoid crash (if issue still exists).

**Comment by manuelsongokuh** [comment]
hello
ALSO problem for TEXTURE, (maybe is problem rendescale)
i put here report error under bash:
:~/Natron.2.0$ sh Natron
Natron
Version: 2.0.0
Copyright (C) 2015 the Natron developers
>>>Use the --help or -h option to print usage.<<<

Natron: line 31: 30539 Errore di segmentazione $DIR/bin/Natron -style fusion "$@"

**Comment by manuelsongokuh** [comment]
where is release stable of 0.7 arena in linux (binary)?

**Comment by olear** [comment]
I decided to just release a 0.8 beta instead, more features ;) (the Read plugins are beta, the rest is 0.7 final)

**Comment by olear** [comment]
I can of course release 0.7 binaries, but they would be the same as 0.8beta minus the Read stuff.

**Comment by olear** [comment]
Fixed in latest Natron2.
