### ISSUE TITLE
geometric transforms (Mirror, Reflection, Wave, Swirl...) should go to the Transform group

### ISSUE THREAD

**Issue by devernay** [olear/openfx-arena#112]
The Filter group is more for plugins that do per-pixel or local operations.
All those (and maybe other) should go to the "Transform" group.
Maybe Mirror is also a bit redundant with openfx-misc's mirror

**Comment by olear** [comment]
Will move to Transform.

The Mirror plugin has some nice effects compared to the Mirror in Misc, a name change or move features to some other plugin?

**Comment by olear** [comment]
I will move the mirror functions to Reflection then remove Mirror, that should be ok?

**Comment by devernay** [comment]
yup sure. What are those nice effects?

**Comment by olear** [comment]
Nothing huge, but some extra mirroring:
![screenshot-21](https://cloud.githubusercontent.com/assets/7461595/8336395/7966684e-1aa4-11e5-9a35-3d5e0c77f8e6.png)

**Comment by devernay** [comment]
oh, this shouldnt be called Mirror, but should be incorporated into Reflection, then!

Mirror is to flip or flop the image, as is necessary when shooting 3D with a mirror rig.

**Comment by olear** [comment]
Ok, easy to mix :)
