### ISSUE TITLE
Texture: unable to disable seed

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#125]
Seed=0 should disable seed and give random noise/plasma etc.

**Comment by olear** [comment]
-1 is random

**Comment by devernay** [comment]
Hi Ole,
I think the "internal" seed should combine the seed parameter with the frame number, as I did in NoiseOFX:
```
    processor.setSeed(hash((unsigned)(args.time)^_seed->getValueAtTime(args.time)));
```
(you'll find the hash function in the code)
If someone wants a texture that doesn't change with time, just add a FrameHold after it (you can point this out in the doc).
The seed parameter should be used to have several texture generators generating different textures at the same time.

**Comment by olear** [comment]
Will look into.
