### ISSUE TITLE
ReadPSD multiplane: get layer real size

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#126]
Get the real layer size, not image size.

**Comment by olear** [comment]
A bit tricker than I though.

When I select a layer in a merge node the following happens:
getClipComponents ... (x 34 times, a bit overkill?)
getFrameBounds ...
decodePlane ...
then getClipComp again x 15

Framebounds sets the image size (if i'm not mistaken), but at that time I don't know what layer to get (that happens in decodePlane), so I can't get the real layer size. Running getFrameBounds in decodePlane will probably don't work ...

**Comment by olear** [comment]
Unable to find a good solution to this problem, delay to v0.9.

**Comment by olear** [comment]
use layer param as workaround

**Comment by MrKepzie** [comment]
The layers are expected to have all the same RoD to work with the multi-plane extension. Otherwise the only viable solution is to disable multi-plane extension support and add a choice indicating which layer to set into the output RGBA channels.

**Comment by MrKepzie** [comment]
In fact the solution is just to take the bounding box of all layers.

**Comment by olear** [comment]
Will some test later today.

**Comment by olear** [comment]
will set bounds to max height/width from layers, that seems to work (better than now).
