### ISSUE TITLE
Layers

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#131]
Hi olear,
Maybe a stupid question, but how to choose a layer in params
Sorry

**Comment by olear** [comment]
You use a merge node or something similar, and select the layer in the channel list.

![screenshot-9](https://cloud.githubusercontent.com/assets/7461595/8502122/7bd7ab2e-21ac-11e5-9d24-af63237649ef.png)
![screenshot-10](https://cloud.githubusercontent.com/assets/7461595/8502124/7eab6c5a-21ac-11e5-8985-63085bfa3840.png)
![screenshot-11](https://cloud.githubusercontent.com/assets/7461595/8502133/81bbff86-21ac-11e5-9734-7621188d5c46.png)

**Comment by olear** [comment]
Btw, will add a "layer" menu in the regular params as well.

**Comment by rcspam** [comment]
ok, thank you.
