### ISSUE TITLE
ReadPSD: icc default profiles not selected in Windows

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#133]
The default selection don't show up in Windows.

On Linux I add "sRGB" as default profile, this catches any profile with sRGB, on Windows it seems it only catch exact match ....

**Comment by olear** [comment]
just add an alternative default with complete name.

**Comment by olear** [comment]
Not that simple, something is strange on Windows .... Debugging on Windows is also hard. I got other .find()'s in that plugin and that works....

No major bug, since everything works, just that the default profiles must be selected before usage.

**Comment by olear** [comment]
@MrKepzie: are default color profiles selected on Mac?
![color](https://cloud.githubusercontent.com/assets/7461595/8531967/3517de12-242b-11e5-9314-7ff79863aa97.png)
Only the RGB stuff is important.

**Comment by olear** [comment]
Seems to happen on Mac as well ....

https://github.com/MrKepzie/Natron/issues/747#issuecomment-124112265

**Comment by MrKepzie** [comment]
Give me a sec, I get a hang in ReadPSDPlugin::restoreState in 
Magick::readImages  when filename is NULL

**Comment by MrKepzie** [comment]
I mean empty

**Comment by olear** [comment]
Seems to be a problem with profiles on mac
![screenshot-3](https://cloud.githubusercontent.com/assets/7461595/8853125/91f48104-3159-11e5-9c92-def743525612.png)

Could be a path I'm missing on Mac, or are the subfolder in that folder maybe...

@MrKepzie : will add a check for filename

**Comment by MrKepzie** [comment]
Ole, here is the ColorSync directory on Mac

**Comment by olear** [comment]
It's empty?

**Comment by MrKepzie** [comment]
Going to send a request with multiple bug fixes wait

**Comment by MrKepzie** [comment]
Here is the screenshot, I got only 1 choice:

**Comment by olear** [comment]
Didn't get a screenshot from your post, but omar posted one
![screenshot-4](https://cloud.githubusercontent.com/assets/7461595/8853659/0c44232c-315c-11e5-849f-c619412cf623.png)

Guess I have to adapt to that structure

**Comment by MrKepzie** [comment]
<img width="228" alt="screen shot 2015-07-23 at 16 56 20" src="https://cloud.githubusercontent.com/assets/4058448/8853733/74c7b1ca-315c-11e5-9a01-acc89395d5df.png">
<img width="1414" alt="screen shot 2015-07-23 at 17 01 54" src="https://cloud.githubusercontent.com/assets/4058448/8853751/8acd5998-315c-11e5-8ad4-8d135a8a4d6e.png">

**Comment by olear** [comment]
Thanks. So Mac don't have a default sRGB profile?

**Comment by MrKepzie** [comment]
Guess not

**Comment by olear** [comment]
Ok, will check for subfolders and update doc about where to download profiles.

This bug will still remain open since the mac stuff was not really related to this issue.

**Comment by olear** [comment]
If I add adobe profiles on Win then CMYK default works, I guess if I change the sRGB default file in Windows that will also show up as default. So no bug .... (just stupid default (if any) profiles on win/mac/lin), users that need this feature will probably have installed profiles anyway (manually or through apps).
