### ISSUE TITLE
Texture: change seed

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#136]
https://github.com/olear/openfx-arena/issues/125#issuecomment-118922866

**Comment by olear** [comment]
This didn't work as expected .... Open Natron, add Texture (use misc/stripes), add 50 frames, push play. Looks good, but zoom in to 100% and press play .... and zoom back again, the seed is all weird.

**Comment by olear** [comment]
screencast: https://fxarena.net/~olear/misc/textureseed.ogv

**Comment by olear** [comment]
Will revert back to old behaviour ...

**Comment by olear** [comment]
Wait, did some tests, it's not the plugin, seems to be a cache problem in Natron(?)

**Comment by devernay** [comment]
did you mark your plugin as framevarying?

**Comment by devernay** [comment]
for Natron, same input + same parameters = same result, except if the effect is framevarying (am I right @MrKepzie ?)

**Comment by olear** [comment]
That I didn't, will fix.
