### ISSUE TITLE
Plugin names should be more unique (add OFX)

### ISSUE THREAD

**Issue by devernay** [olear/openfx-arena#137]
A few plugins in openfx-arena have exactly the same name as existing plugins in Nuke (there may be a similar problem with Fusion or other OpenFX software). The consequence is that only one version is available to the user (e.g. Nuke's Tile becomes unavailable because of openfx-arena's Tile).

A good idea is to add the suffix "OFX" to the name of all plugins that already exist in other software (or to all plugin names). Natron silently removes this suffix. If you want to use another suffix than OFX, ask the https://github.com/MrKepzie/Natron team and we'll suppress it too. If you prefer a prefix (as it is done in Furnace or Sapphire), we can do it too.

**Comment by olear** [comment]
Ok, will add OFX suffix.

**Comment by olear** [comment]
Text has the OFX suffix in the name in latest Natron.

**Comment by devernay** [comment]
Natron bug, then!
