### ISSUE TITLE
LensDistortion

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#139]
Add more distort plugins, at least Barrel (in trunk) and Affine.

* http://www.imagemagick.org/Usage/distorts/#barrel
  * http://www.imagemagick.org/Usage/lens/
  * http://www.imagemagick.org/Usage/distorts/#barrelinverse
* http://www.imagemagick.org/Usage/distorts/#affine
  * http://www.imagemagick.org/Usage/distorts/#affine_projection

And probably more ...

**Comment by devernay** [comment]
CornerPin already does Translate (enable 1 point), Translate+Rotate+Scale (2 points), Affine (3 points) and Homography (4)

Besides, the transforms from cornerpin can be concatenated (if there are 2 consecutive transforms in the graph, only one interpolation is done, see Nuke user manual)

The Barrel transform (direct and inverse) would better fit in the LensDistortion plugin: just add the distortion model to the plugin, and voilà. LensDistortion also concatenates transforms.

**Comment by olear** [comment]
Ok, drop Affine (may add features from that to the Text plugin to add more fancy shadow effect)

Drop Barrel as well?

**Comment by devernay** [comment]
it would be better to have barrel n the lensdistortion plugin (it's easy, if you figure out the formula), in order to factorize all distortion modules (LensDistortion already does barrel distorton)

**Comment by olear** [comment]
LensDistortion exists, and barrel is not needed(?).
