### ISSUE TITLE
Feature Request - Mask Inputs for Filter Nodes

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#144]
Can Transform and Filter nodes like the Tile, Swirl, Wave, Oil Paint, Charcoal and Sketch nodes get a mask input feature?

Thanks
Omar

**Comment by olear** [comment]
Ok?:
![screenshot-5](https://cloud.githubusercontent.com/assets/7461595/8863625/9ebec66a-319a-11e5-9a36-4eb8aa8c2339.png)

**Comment by olear** [comment]
Adding mask to Wave hit #58 , will find a workaround.

**Comment by olear** [comment]
I guess this is how it should work:
![screenshot-7](https://cloud.githubusercontent.com/assets/7461595/8864325/c884e5b4-31a0-11e5-91f0-3316034f5a82.png)

**Comment by olear** [comment]
Please test Charcoal and Sketch, not sure the result is what it should be ...

**Comment by olear** [comment]
Invert mask also?

**Comment by olear** [comment]
Invert didn't works as expected, so drop that. 

That should be it, please reopen if I did something wrong :)

**Comment by blackearth2014** [comment]
For your nodes I don't think the Invert Mask is needed as of now because we have he Invert node. I will check out the Charcoal and Sketch before I go on Vacation.  Thanks for the rapid implementation.

**Comment by olear** [comment]
The invert mask function didn't work as expected either, so the Invert node is the best option.
