### ISSUE TITLE
Alpha Generation after node is disabled

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#150]
Ole,

Your nodes generates an alpha channel if you don't want it. If you disable the node and press "a", you get a white alpha channel in the viewer. Is it suppose to be this way?

**Comment by olear** [comment]
All plugins are RGBA.

**Comment by blackearth2014** [comment]
Okay I understand, but if I disable your node and my ReadOIIO node is in RGB, there shouldn't be an alpha present. When I disconnect your node the alpha channel disappears. Is this normal?

**Comment by olear** [comment]
A but unsure, seems like something the host controls. Will check.

**Comment by olear** [comment]
Confirmed, but this is not controlled by the plugin.

I can of course add support for RGB.

**Comment by olear** [comment]
This is controlled by host. Since the plugin is RGBA-only you will always have an alpha, unless you remove the node, or add a shuffle.

Add a new issue if you want RGB support in plugins.

**Comment by blackearth2014** [comment]
Now that I know that this is how the plugins work, then I can explain it better when I do more demos. No need to change. Thanks for getting back to me.
