### ISSUE TITLE
TextPango issue

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#152]
Hi Olear,

After enter text somewhere in the 'markup canvas', move it with mouse doesn't update viewer !
Here a [screenshot](https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-07-28_16.45.48.mp4)

**Comment by olear** [comment]
ctrl+enter

**Comment by rcspam** [comment]
I thought a click out of markup canvas was sufficient.

**Comment by olear** [comment]
btw, fixed white bg on first run.
