### ISSUE TITLE
Mac: (deployment) issues

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#154]
Currently there are (deployment) issues with fontconfig on Mac, find a fix/workaround/something.

**Comment by devernay** [comment]
Could you give details on comment on why you think it's related to finding?
As long as text OFX works, I would say that fontconfig works too

**Comment by olear** [comment]
TextOFX don't need a font cache to get fonts (just need a path), but pango/librsvg2 does.

**Comment by devernay** [comment]
I took the config file from inkscape, and the cache stuff looks right to me. Do you see anything wrong in it? Or maybe I also have to set up another environment variable than FONTCONFIG_PATH for the cache to work properly?
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by olear** [comment]
Something must generate the cache, like fc-cache. On Windows (and Mac) this is a problem, you either have to run fc-cache or make your own cache generator.

Will read up on fontconfig and see if I can make a simple function that can be added to TextPango/ReadSVG.

**Comment by devernay** [comment]
Does that mean we have to bundle fc-cache? I'll check how gimp and inkscape do this

**Comment by olear** [comment]
gimp generates font cache on startup, but the don't use fc-cache directly, so they probably have their own function for doing that.

**Comment by olear** [comment]
Will just strip down fc-cache to a simple function, seems the easiest solution (?) Couldn't find that many examples on cache generation.

**Comment by devernay** [comment]
Take a look at gimp's code in app/text/gimp-fonts.c it doesn't do anything different than Imagemagick. IM calls FcInitLoadConfigAndFonts, which breaks down into FcInitOwnConfig and FcConfigBuildFonts (see fc/fcinit.c in fontconfig source).

Gimp calls FcInitOwnConfig and FcConfigBuildFonts. Nothing about the cache in gimp.

FcConfigBuildFonts (fc/fccfg.c) calls FcConfigAddDirList, which calls FcConfigAddCache. Cache handling and updating is done *automatically* in fontconfig.

Probably the culprid is somewhere else, like a hardcoded config path in pango (that thing is really a mess)

**Comment by devernay** [comment]
see also https://github.com/videolan/vlc/blob/master/modules/text_renderer/platform_fonts.c for another example (which works also on windows btw)

**Comment by olear** [comment]
Thanks for the info, I read the gimp stuff earlier, but wasn't sure that had anything to do with the cache.

Will do some tests (on Windows).

**Comment by olear** [comment]
Got font cache generation working, but it's slow on first run, so maybe a button or something is needed? or a way to inform the user (I output to terminal) when this happens.

**Comment by devernay** [comment]
Do it in the render function and use the progress suite?

**Comment by devernay** [comment]
So what function had to be called?
We could also do it when launching Natron, so that the plugin spends no time in it.

**Comment by olear** [comment]
Almost too simple:
```
        FcConfig *fcConfig = FcInitLoadConfig();
        FcConfigBuildFonts(fcConfig);
```

Worked on Windows (well, the cache was generated, font selection on Windows works without cache it seems).

Doing it in Natron would be the best, since then we avoid several plugins doing the same scan. Could you test that this actually works on Mac in combination with TextPango?

**Comment by devernay** [comment]
.. But IM was already calling FcInitLoadConfigAndFonts, isn't it?
So why is this necessary?

**Comment by olear** [comment]
Did https://github.com/olear/openfx-arena/commit/87af694be9d335b524a15b78df6a2974ae05efb6 have any effect on TextPango? @devernay,  @blackearth2014

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/issues/178#issuecomment-141303205

**Comment by olear** [comment]
Still font issues with pango/svg?

**Comment by blackearth2014** [comment]
The Mac version of Natron are still having deployment issues. Alex said that Fred has not finish working them out yet. I am hoping by this sunday it will all be fine. I would hate to use another compositor in the middle of my film project for a festival that I am entering.

**Comment by olear** [comment]
Understand, will keep this open until someone confirms that pango+svg works with freetype/fontconfig.

**Comment by blackearth2014** [comment]
Thanks

**Comment by devernay** [comment]
my guess is that it should be fixed by tomorrow.

**Comment by blackearth2014** [comment]
TextPango is now working on my Mac. Thanks to everyone who has been on their grind to get it working.

**Comment by olear** [comment]
Awesome, big thanks to @devernay for making it work on Mac.

@blackearth2014 just ask if you need help with markup etc in Pango.

**Comment by olear** [comment]
Btw, could you also check that fonts work in ReadSVG?

**Comment by blackearth2014** [comment]
I did last night unless I must be doing something wrong. I type a phrase in the text box and save as a SVG file.  Is there something that I am doing wrong or can you provide a step by step tutorial?

**Comment by olear** [comment]
Just type something and save....

![snapshot13](https://cloud.githubusercontent.com/assets/7461595/10076021/622ee9d0-62d9-11e5-937c-6cc2e1219342.png)

**Comment by blackearth2014** [comment]
It's working perfectly. It was my error. Thanks.

**Comment by olear** [comment]
Great :)
