### ISSUE TITLE
ReadSVG node: Not reading text spline data from Inkscape.

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#155]
Hello Ole,
I did some further beta testing of your ReadSVG node. Apparently,it is not reading any text spline data. It is only reading shape data. I hope a fix for this in V2 release or at lease for 2.1 will be available. See attached images for beta test references.

![screen shot 2015-08-02 at 1 00 23 am](https://cloud.githubusercontent.com/assets/7956901/9024794/ab7f1a0c-38b2-11e5-82d9-4d728a836e40.png)

![screen shot 2015-08-02 at 1 00 23 am 2](https://cloud.githubusercontent.com/assets/7956901/9024795/ab8121da-38b2-11e5-86ab-52738208d302.png)

**Comment by olear** [comment]
Text is only supported if path.

**Comment by olear** [comment]
My bad, fonts etc are supported.

![screenshot-10](https://cloud.githubusercontent.com/assets/7461595/9026946/7b0703b8-3942-11e5-857f-9efd8cb0dddb.png)

This is probably a Mac deployment issue ( #154 ) related to fontconfig.

**Comment by blackearth2014** [comment]
How can I reconcile this fontconfig option on my Mac? I still have to use objects to paths in Inkscape.
