### ISSUE TITLE
i did need 'brightness' in Roll..

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#157]
hello
i need so much "brightness" in Roll, it's possible? because i add many node but not good for me result..
but for now i need brightness in Roll for moment.. i dont know will in all plug.. but for now i'm not know ok?

but not for opacity.. it's brightness effect true result ok?

**Comment by olear** [comment]
Possible, but I don't see the point. You should use a dedicated node for brightness.

**Comment by manuelsongokuh** [comment]
you have find node "brightness"?
see example AE have "brightness", in natron have not it alone brightness...
![image](http://www.surfacedstudio.com/wordpress/wp-content/uploads/2014/06/After-Effects-CC-New-Features-06-Effect-Mask.png)

**Comment by olear** [comment]
There are several color node that can alter brightness.

I can add a "modulate" node with support for brightness, contrast and saturation, but I don't know if that just overkill compared to the other nodes available in openfx-misc(?)

**Comment by manuelsongokuh** [comment]
ok, i try other node color, you can wait a moment ok?

**Comment by manuelsongokuh** [comment]
i did not find "brightness" but i find "brightness" from node HSVTool but it's not true brightness..because there are not change from value 0 to -100 (to back total)...HSVTool has only value to 1 like as WHITE total.. but not black..

maybe gain or gamma is same "brightness"...?

**Comment by manuelsongokuh** [comment]
see my issue old, there are screenshot of AE adobe there is "brightness" but is insert each all plugs..
go to see https://github.com/olear/openfx-arena/issues/45#issuecomment-118168070

**Comment by manuelsongokuh** [comment]
i thinking....
you can add node name "brightness & contrast" default value is 0, to white value is 1, to black value is -1, simple, RGB, option for RGBA. i dont know what is best code: imagemagick or OFX or OFOIO, important is FASTER RENDER ok?

**Comment by olear** [comment]
https://fxarena.net/~olear/Modulate.ofx.bundle-1.0-Linux-x86-release-64-OpenCL.tgz

Supports OpenCL if you got it.

Note! I can't change anything with this node, take it or leave it ;)

**Comment by manuelsongokuh** [comment]
WOOW... but it's NEW or already exists???

**Comment by olear** [comment]
Added it now, it adjusts brightness, saturation and hue. Simple (can maybe add contrast). 

Should run real-time if you got a ok OpenCL gfx card (untested, don't have OpenCL on this laptop).

**Comment by manuelsongokuh** [comment]
YOU ARE REALLY MAD!!!!! :+1: :+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
YOU ARE MONSTER :+1: :+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:
THANK YOU BILLION  :+1: :+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1::+1:

**Comment by manuelsongokuh** [comment]
TESTET WORKED OPENCL! BEST!

**Comment by manuelsongokuh** [comment]
@olear this named modulate can port in your bundle of openfx-arena? or future bundle arena..?
