### ISSUE TITLE
OpenFX-Arena 1.9.0 binary for Linux..?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#159]
OpenFX-Arena 1.9.0 binary for Linux..?

**Comment by olear** [comment]
Natron has lastest OpenFX-Arena bundeled on Linux/Mac.

```
Maintenance release primarily aimed at Windows users. Linux and Mac binaries are provided through Natron (v2).
```

**Comment by manuelsongokuh** [comment]
ok but i have not find last data snapshot 6 july... there is 3 july is old...
http://downloads.natron.fr/Linux/snapshots/64bit/files/

**Comment by olear** [comment]
Build server is down or something. Try this while you wait: https://downloads.natron.fr/~olear/Natron/Natron-1d08991f7a2e24d086881c29b638461dd9db846e-Linux-x86_64bit.tgz

**Comment by manuelsongokuh** [comment]
maybe limited for traffic data monthly?

**Comment by olear** [comment]
No, the build server is private. I don't know what the problem is, I don't have access to that server. 

Will be fixed :) (worst case I do some builds)

**Comment by manuelsongokuh** [comment]
ok, dear, i dont see "Modulate" in last snapshot...(you did sent me link)
your information write "added optional "modulate" plugin" from link  https://github.com/olear/openfx-arena/compare/0.8.1...1.9.0
your plug is latest 1.9.0 in latest natron?

**Comment by olear** [comment]
Modulate is optional (not included in bundle). I'm a bit unsure if Modulate should be included as default, openfx-misc has many color nodes.

https://fxarena.net/~olear/Modulate.ofx.bundle-1.0-Linux-x86-release-64-OpenCL.tgz
