### ISSUE TITLE
readSVG: pan,zoom...easy..from HAND?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#161]
hello

i do TEST for readSVG (test tress)..
*********

Test 1: create a VIDEO from SVG, "ZOOM INFINITE"..

how?
readSVG>>DPI: 2000, from 1 frame
readSVG>>DPI: 1, from 200 frame

RESULT/PROBLEM:
IT'S NOT GOOD: slow SLOW SLOW SLOW SLOW...
(used node: trasform (position), scala: readSVG use "dpi"..)
this TEST 1, is failed.   ....why?

see example number 1:
http://ariutta.github.io/svg-pan-zoom/demo/inline.html
you use click "+" and "-" for zoom, you click and drag like as PAN ok?
IT'S FASTER than readsvg or natron (not know..)

see example number 2:
http://www.xara.com/us/designer-pro/advanced/
go to "ZOOM"  and click "play of video" there is FASTER for RESULT to SHOW VIEWER.
is FASTER than readsvg or natron (not know..)
*********

TEST 2: comfort WIP (work in progress)?

RESULT/PROBLEM:
worked, but long time to job..
needed: easy to use and save a lot of time of jobs (WIP)..

example:
PAN...(use node transform...it's right?...long time to use my mouse position...long lost time)
ZOOM ....(use node readsvg>>dpi...it's easy to know KNOWLEDGE OF "DPI"?)
then.. see example of number 1 (http://ariutta.github.io/svg-pan-zoom/demo/inline.html)
IT'S EASY TO USE WITHOUT LOST TIME FOR "KNOWLEDGE DPI"...they said "PAN, ZOOM" it's true EASY and FAST to UNDERSTAND..right or not?
*********

first of all:
I don’t hate... I want to care of this READSVG but needs go to BEST to USE IT..
I bring my thoughts and reports here,, open mind... ok?
:+1: :+1: :+1: :+1: :+1: :+1: 

:-)

**Comment by olear** [comment]
ReadSVG converts vector to bitmap, you don't work with vectors, the higher DPI the slower it gets to load the image (since you increase the image size).

If you want to animate vector images you should set the DPI to the highest image size you need, and then use a transform node to adjust the size (scale down).

**Comment by manuelsongokuh** [comment]
hello,
i did test for animate vector under dpi, is CRASH..
how is crashed? start set dpi: 2000 for first frame, last frame 200: set dpi: 1,
cpu full load, 2minutes will closed natron like as CRASH..

i dont know..maybe too large pixel...
you can expected not convert (from vector to bitmap (raster)), keep vector original? like ase new engine cairo (used inkscape)...?
for Raster is ok for small and medium size of pixel, but not good for large og pixel (depend of project) my case for TEST (like as Xara Zoom Video) here http://www.xara.com/us/designer-pro/advanced/   do you did see the video from xara site "zoom"? that is beautiful from microscopes to woman in bathtub , that is surprise like as "impressed" to WATCH VIDEOM effect ZOOM of vector...

i can look for programming code in google search and give you information? for what? for IMPROVE ok?

**Comment by manuelsongokuh** [comment]
hello, i can ask you:
are you able add cairo engine port in natron for vector powerfully? 
https://en.wikipedia.org/wiki/Cairo_%28graphics%29

**Comment by olear** [comment]
Natron already uses Cairo for several functions, but not for images. 

Vector graphics is not a standard in applications like Natron, everything is bitmap. ReadSVG will always read the vectors and return a bitmap (based on your param), this will not change.

**Comment by manuelsongokuh** [comment]
ok, but ROTO is a vector? what is engine backend? possible it's from cairo?

**Comment by olear** [comment]
As said, Natron already uses Cairo (in roto etc). And ReadSVG uses Cairo+librsvg to convert SVG to bitmap.
