### ISSUE TITLE
what i will do...with this error?....(polar)

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#162]
hello
i reopen my old file ntp and there are messages:

WARNING: The node Polar1 (net.fxarena.openfx.Polar) version 1.1 was found in the script but was loaded with version 3.0 instead

WARNING: The node Roll1 (net.fxarena.openfx.Roll) version 1.0 was found in the script but was loaded with version 2.0 instead

Polar1: Could not find a parameter named polarRotate

Polar1: Could not find a parameter named polarFlip

Polar1: Could not find a parameter named virtualPixelMethod

Polar1: Could not find a parameter named Output_channels

Roll1: Could not find a parameter named rollX

Roll1: Could not find a parameter named rollY

Roll1: Could not find a parameter named Output_channels

Roto1: Could not find a parameter named NatronOfxParamProcessR

Roto1: Could not find a parameter named NatronOfxParamProcessG

Roto1: Could not find a parameter named NatronOfxParamProcessB

Roto1: Could not find a parameter named NatronOfxParamProcessA

Roto1: Could not find a parameter named Output_channels

Merge2: Could not find a parameter named Output_channels

Constant1: Could not find a parameter named Output_channels

Merge1: Could not find a parameter named Output_channels

Roto2: Could not find a parameter named NatronOfxParamProcessR

Roto2: Could not find a parameter named NatronOfxParamProcessG

Roto2: Could not find a parameter named NatronOfxParamProcessB

Roto2: Could not find a parameter named NatronOfxParamProcessA

Roto2: Could not find a parameter named Output_channels

Grade1: Could not find a parameter named Output_channels

maybe i will add issue to Natron github?

you want i add file ntp?

**Comment by manuelsongokuh** [comment]
it's possible "REPAIR" code in ntp for plugins (changed)?

**Comment by olear** [comment]
Sure, but the plugin names and/or params may need to be changed. Will have a look when I get the time.

**Comment by manuelsongokuh** [comment]
yes, of course, its old code of plug but this is "delicate" situation...
why? ....because if i work my job big project like as production movie or short movie, i save file ntp and future re-work my jobs will be lose data of plug ins...this i think needs to repair or convert..
i dont know how does best way for repair..this is case very delicate...right?

**Comment by devernay** [comment]
You should always keep the version of Natron + plugins which you used to make a project.
We try to maintain backward compatibility as much as we can, but I don't think openfx-arena should try to maintain backward compatibility with projects done before ofx-arena 1.0

**Comment by olear** [comment]
The project is from when arena was in flux. Some plugins are gone, and some changed params.

Projects created  with 0.8+ should be safe. But lower will probably break...

Also, snapshots should not be used in production, at least stay with that version until done.

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/releases/tag/0.7Beta3

Is the last release with the Distort plugin.

**Comment by manuelsongokuh** [comment]
@olear ok, i understand for situation for 0.8+ etc etc, but i wanted to say you, when you will create new code for plugin and need be retro-compatible, or auto-correct/auto-convert/auto-repair --->>>  if finded plugin old. this mean you remember for future for this case situation ok?
for now plugins are stable that ok, if future plugins changed some/any code SO need to check if can auto-correct ok? this is very important...because who had used plugins for big project heave or little project, this is happen situation ok? for my case my project heave i do "start over" not problem for me, but someone used and risk lose data of plugins...
i hope you remember for future of this situation case ok?
good luck!
@olear @devernay @MrKepzie are BEST PEOPLE!

**Comment by olear** [comment]
I always try to be compatible, but Distort was a test plugin, and was later split into individual plugins. Some of the plugins split from Distort had the old param name and during the beta testing of 0.8 was changed to their proper name.

The current plugins are "api" stable, and will only get bugfixes or new features (but existing features will stay untouched). New plugins will be in flux until marked as stable, and will probably change/break several times during development, that's just how it is :)

**Comment by devernay** [comment]
You *should* be able to install the older version of ofx-arena in another directory (say /Library/OFX/Plugins/openfx-arena-0.7b3 if you are on Mac, /usr/OFX/Plugins/openfx-arena-0.7b3), and Natron *should* load the old version when you load an old project, and the new version when you create a new node.

You should be able to get the best of both worlds.

Can you check if it works?

If not, it's a bug (we didn't test much this feature)

**Comment by manuelsongokuh** [comment]
@devernay that old plugin save other folder, i go to preference natron for add path of plug in (old) it's worked.. then can need add information in documentation in future if case (old plug in) i know it's few/minor cases ok? this is not a bug. resolved : other folder for old plugins. :+1: 

@olear of right, i did say you in past months i did split into invidual plugins will be sure and Stable ok? :-) :+1:
