### ISSUE TITLE
Displacement plugin

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#163]
see particular displace of IM:
http://www.imagemagick.org/discourse-server/viewtopic.php?t=16921#p62696

that cool shirt but i dont know it good for in VIDEO ...??
but good trick...right?

**Comment by olear** [comment]
So you want a node that does displacement using a mask?

**Comment by manuelsongokuh** [comment]
yes mask but also distort or displace effect..but you have already wrap IM right? but i'm not sure for this because will be not performace during render...

**Comment by olear** [comment]
Ok.

**Comment by manuelsongokuh** [comment]
ok i can add other information here for displacement?

**Comment by olear** [comment]
The original link should be enough info.

**Comment by manuelsongokuh** [comment]
ok i will add here link screen record for you interesting ok?
https://mega.co.nz/#!S4dn0ZyQ!bpGRCoYEIGnb0Tb3sMdlMh2ZibrcIUmNRKENKwMw6xY

for displace map i think need separate:
1- source image (read, nodes,group,etc) this is normal imput
---link---
2-displacemap:  (node-of-IM)
source1: that image from roto or noise or other effect (mask,wrap) this is for progress effect.
source2: that image from source image, this is progress from image to effect..
output1: result effect. GOAL.

ok?

**Comment by manuelsongokuh** [comment]
![explain-01](https://cloud.githubusercontent.com/assets/12126929/9289214/5bcd092c-4368-11e5-8e47-3ba24373c06f.png)

**Comment by olear** [comment]
Did some tests with DisplaceCompositeOp, but didn't work as expected yet ...

**Comment by blackearth2014** [comment]
Natron has an Idistort node. Doesn't it do the same thing?

**Comment by olear** [comment]
You're right, I didn't check for existing plugin, only respond to the issue, my bad.

@manuelsongokuh : check in Natron before requesting new features.

**Comment by manuelsongokuh** [comment]
ok for closed, but i'm not sure for idistort, because that video (i did send link) is not same for idistort..maybe i'm wrong for displacement of IM..
aftereffect has turbulence, this is very important for effect motion graphics, effect fx. 
if natron have idistord so i want not loste big time for hand..for this i want natron will be best help for all compositor..

@blackearth2014 : did you see my link ?

**Comment by olear** [comment]
Tested iDistort, but can't replicate the "t-shirt effect", maybe I'm using it wrong ....

**Comment by manuelsongokuh** [comment]
in fact i did say displacement IM for t-shirt, anyway, i'm not know for find best way for effect..

sorry i ask you precise: you are able something to use 'turbulence' ? because AfterEffect have many used operator "turbulence".. maybe that turbulence are beneficence million effects..this is true missed for natron..

you are able what use code: c++? opencv?

**Comment by olear** [comment]
Will look more into this request (if this warrants a new plugin) after Natron v2 release.

**Comment by manuelsongokuh** [comment]
hi, is there news about this?
