### ISSUE TITLE
BIG size in /tmp/....what? total 12gb!!

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#164]
hello
i find a thing, it are not right...maybe itìs crazy from imagemagick?
see my screen shot:
![natron-magick-tmp-big](https://cloud.githubusercontent.com/assets/12126929/9317959/5fdbfd9c-453f-11e5-9e29-c077ebcc5a9a.png)

but there are any to clean all cache or tmp of imagemagick under plug of arena?
maybe needed:
1 - when natron will close(NOT crashed) THEN needed to delete/clean all cache/tmp in /tmp. 
2 - when natron will closed (YES crashed) THEN when start-up natron does always: THEN NEEDED to check to delete/clean all cache

this is could be good operation for free disk..
my case is 12GB in tmp...named:
file:///tmp/magick-2210bDB5UFWpPNnF
file:///tmp/magick-2210faQEQZ9TaHTG
file:///tmp/magick-2210KpzN9he2qymQ
file:///tmp/magick-2210tRRJOtjObfmj
file:///tmp/magick-2210vODN0KLB1J8a

or maybe you contact MrKepzie for add to clean to start-up natron always..?
you and MrKepzie can find other solution ok?

NOTE:
magick-xxxxx i believe : it's for plugins of arena or no? so i open this issue..

thank you

**Comment by olear** [comment]
Will check, thanks for reporting.

**Comment by olear** [comment]
No files in /tmp here.

**Comment by manuelsongokuh** [comment]
ok, who are them? it's from imagemagic?..

**Comment by olear** [comment]
Delete them, and test a arena plugin in Natron, do you get new magick-* files in /tmp?

**Comment by manuelsongokuh** [comment]
ok i will try, i will do report here..ok?

**Comment by olear** [comment]
Did you get new magick files?
