### ISSUE TITLE
ReadPSD Node: File Import Resolution Bug/Issue

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#165]
Hello Olear,

The latest update for Natron I have notice that the ReadPSD node is adding more size resolution on files that were created at 1920*1080. I have a test image that was created in Krita and Gimp at 1920*1080. The ReadPSD node see 1984*1216 every time. The attached image shows the proof of the bug/issue.

![readpsd_resolutionerrors](https://cloud.githubusercontent.com/assets/7956901/9348644/f8120232-4607-11e5-8c4e-848e617b2f19.png)

**Comment by olear** [comment]
Multiplane only supports one image size, so I need to scan each layer and set the image size to the largest layer size, that' why you get padding.

**Comment by blackearth2014** [comment]
Okay but every layer in the posted image was created at FullHD. All layer sizes are the same. Why do I still need padding.

So the only work around is to use shuffle nodes and everything back together?

**Comment by olear** [comment]
Padding should only happen if one layer is bigger than the others, or if the layer have an offset (you moved the layer beyond image bounds in gimp/krita etc.

If not please send me a link (here or in private) with a test image.

**Comment by blackearth2014** [comment]
Okay. Got it now. So when I load the file again in Natron and the resize node doesn't fill the screen, it's the layer offset.

Now will you have time for creating documentation for the other features in the ReadPSD node for clarification?

**Comment by olear** [comment]
Will add some documentation :)

**Comment by blackearth2014** [comment]
Cool breeze.
