### ISSUE TITLE
TextPango Ndoe: Will there be a Mac Relief

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#166]
Hello Olear,

I have tried every thing to my knowledge and technical skills to get the TextPango node to work on the Mac and I still get square boxes. Will the TextPango nodebe stripped from the Mac release for V2?

**Comment by olear** [comment]
Duplicate of #154 

Don't know, I did some changes but got no feedback, so reverted the changes.

**Comment by blackearth2014** [comment]
I think I'd missed this. I know nothing about coding. What do I need to do?

**Comment by olear** [comment]
Ok, will add the code again ...

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/commit/6fb35ccb26e72ef3966637f76575323cf829bbc8

Please test when mac binary is ready.

**Comment by blackearth2014** [comment]
Thanks

**Comment by blackearth2014** [comment]
By the way, do you know when the next build would be. There hasn't been a build within nearly 24hrs. There are usally 4 a day.
