### ISSUE TITLE
Glass Refraction Filter: Request

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#169]
Is it possible to implement a Glass Refraction Filter that does't require a 3D environment. Its something like the I-Distort and BilateralGuided nodes combined with a Source, UV, Mask and bilateral blur filter controls. If that make since.

**Comment by olear** [comment]
request noted, will start on a new batch of plugins after Natronv2 is out.

**Comment by olear** [comment]
Probably a better request against the openfx-misc plugins. Or maybe possible with the new GMIC plugins.

**Comment by blackearth2014** [comment]
Cool Breeze
