### ISSUE TITLE
node ROLL: how i can do clone move to other node?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#170]
hello

node roll is ever potential, i use many times!
so i need to ask you for help me or change code( it's depend from you)
then:

when i add node roll and i move x or y or xy both, take all data of moving (like as copy data of moving) to other node:
- transform
- roto(layout will be moving..)

i dont know how i do...maybe use to python script?
do you have idea?

**Comment by olear** [comment]
edit=>clone don't work?

**Comment by manuelsongokuh** [comment]
sorry i'm not understand.. you can explain me step step..sorry me

**Comment by olear** [comment]
You can clone nodes (right-click the node you want to clone, select edit and clone):
![clone](https://cloud.githubusercontent.com/assets/7461595/9528693/4323ec3c-4cf6-11e5-9514-7ddada3c81c4.png)

**Comment by manuelsongokuh** [comment]
i dont said copy or clone in nodegraph.. i mean:
copy data from NODE ROLL to NODE ROTO for automatic moving from NODE ROLL, maybe need add script pyton..but i dont know of pyton script..

example:
node roto i add script:
y=y of roll
x=x of roll
do you undy?

**Comment by olear** [comment]
then you must use python, see screenshot:
![pyclone](https://cloud.githubusercontent.com/assets/7461595/9528930/b8d6315a-4cf7-11e5-90c4-1d22775dd906.png)

**Comment by manuelsongokuh** [comment]
ok that is ok, but different number..
see:
![natron-roll-suggest](https://cloud.githubusercontent.com/assets/12126929/9529246/811e2cb6-4cf9-11e5-93f6-c397eac95d52.png)
color red (rectangle) is roto cloned y from roll but is out scene...
Roll3.y.get()-Roto4.y.get ?

**Comment by manuelsongokuh** [comment]
why you did close without resolve...?

**Comment by olear** [comment]
Not a openfx-arena issue.

**Comment by manuelsongokuh** [comment]
ah, you are right! sorry me. i will ask to WHO? i'm not expert python script...where i will ask forum? forum python?

**Comment by olear** [comment]
I'm no python expert myself, I would recommend asking on the forum (user help/python category).

**Comment by manuelsongokuh** [comment]
ok.. thank so for create node ROLL thank you!
