### ISSUE TITLE
it's possible new plug name particular?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#172]
it's very potential effect for many effects high professional..
this particular used AE, you have idea for create it?

**Comment by olear** [comment]
Been looking at various 3D stuff and will probably add some new plugins based on that, but a particular system is too much at the moment...

**Comment by manuelsongokuh** [comment]
ah, wow that particular for arena will be dangerous for fans natron... :+1:  :+1: 
see various example..
https://www.redgiant.com/products/trapcode-particular/
http://www.premiumbeat.com/blog/10-amazing-trapcode-particular-tutorials/
https://www.videocopilot.net/proshop/plugins/trapcode_particular/

**Comment by manuelsongokuh** [comment]
"will probably add some new plugins based on that"
did you mean, you did try to add new plugins?
i can help you for report or find bugs?

**Comment by olear** [comment]
I have not done any OpenGL before, so I'm currently (trying to) creating some plugins using that.

Skills to do a particular system is not present yet ...

**Comment by devernay** [comment]
@olear check out TestOpenGL in openfx-misc.
Natron doesn't support OpenGL rendering, but I managed to compile it with Mesa (a special mangled version where all functions are prefixed by 'b' so that you can also link with OpenGL)
take a look at that GIST (you probably won't need the mac patches) https://gist.github.com/devernay/71f3d7661d910e6494a9 for compiling mangled osmesa.

**Comment by manuelsongokuh** [comment]
@devernay 
i ask what is used opengl from blender?

**Comment by olear** [comment]
@devernay Thanks for the info, will check out TestOpenGL.

Currently I'm just learning the basic of OpenGL, a bit confused by the window stuff (glut etc), so I made a basic cmd app that setup the context manually (no glew etc) and uses a frame buffer on GLX (I know, not portable, but I get around the window issue), then draw something and output the "image" (glreadpixels) to a float and write that to a png using IM.
