### ISSUE TITLE
Add a "Looks" node

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#173]
hello

i'm forget to tell you for information helpful and cool, maybe you hands said "it's easy to code"
(i joke) then go to see link effect copy as instagram, for gimp:
http://registry.gimp.org/node/28613
http://pixovert.sonovert.com/index.php/gimp/114-create-an-instagram-style-vignette-in-gimp-sp-838.html

this is effects of instagram
![link-image](http://registry.gimp.org/files/gimp_instagram.jpg)

this is good, but not know..you could to choose ok?

is a joke "we can make a video of the same effects instagram, why not? it's a challenge?"

**Comment by olear** [comment]
I think it would be best to use existing nodes and just make a "preset" on each effect...

**Comment by manuelsongokuh** [comment]
ok good idea but there is preset?

**Comment by manuelsongokuh** [comment]
did you try on gimp instagram?

**Comment by manuelsongokuh** [comment]
https://debarshiray.wordpress.com/2016/03/08/gnome-photos-3-20-0/

**Comment by olear** [comment]
So, I have (made) a small collection of "Looks" filters in OpenCL. I will add a new node named "Looks" this weekend if I get the time.

This will be a basic node with a collection of presets, nothing more.

**Comment by manuelsongokuh** [comment]
OH thank you!
i will wish test it..when?

**Comment by olear** [comment]
done, just have 5 presets at the moment, will add more later.

**Comment by olear** [comment]
So, I changed my mind and will start this plugin from scratch. I will use the film emulation presets found in GMIC, there are already 300+ presets available. Will try to finish the plugin this weekend.

**Comment by devernay** [comment]
note that there are also many looks in the blender OCIO config (available through OCIOLookTransform)

**Comment by olear** [comment]
I noticed that, but not as many as in GMIC. And I also don't know how to create new presets/looks for OCIO, using haldclut is much easier (for most people).

http://gmic.eu/film_emulation/

**Comment by olear** [comment]
I finished the plugin on Saturday, but the colors in Natron are all wrong. Applying the filters from the commandline using convert work fine, also using a test cpp with the same code as in the plugin.

Will try other hosts to see if this is a generic issue.

**Comment by devernay** [comment]
Ole, these "looks" should probably be applied to sRGB, not linear

**Comment by olear** [comment]
Ahh, that's probably the issue. Thanks.

**Comment by olear** [comment]
The plugin is more or less done (on Linux). Will commit after I have tested the other platforms.

**Comment by manuelsongokuh** [comment]
hi where i can download for try it?

**Comment by olear** [comment]
I have not commited the plugin yet, so you can't download it. I will commit the plugin after I have tested it on all platforms. 

There is also a bug in IM6 related to this plugin, so it only works reliable on IM7 at the moment 

This plugin will not be added to Natron until IM6 is fixed, or we move to IM7 (but IM7 creates issues in the other plugins... happy, happy, joy).

**Comment by olear** [comment]
@manuelsongokuh : http://downloads.natron.fr/~olear/wip/HaldCLUT-1.0beta.ofx.bundle-Linux64.tar.gz
