### ISSUE TITLE
Strobe effect node: B/W and Color specific controls

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#174]
Is it possible to implement a strobe effect node that only effect certain pixel values of an image. For example, a B/W image that can strobe certain luminance values and for a color image a certain hue range value. This way we don't have to use a bunch of HSVTool nodes.

**Comment by devernay** [comment]
can you please explain more in detail ?
I'm not familiar with what you call "strobe" (I guess this dates from analog video mixers, right?)
why doesn't hsvtool solve this? it gives a mask which you can use for masking a merge.

**Comment by blackearth2014** [comment]
Yes, this is from the analog days of video mixers. I just wanted just a little more control just using one node. The strobe only affects the overall image. If you have a B/W image, there can be a histogram slider that controls the only High and Low luminance ranges with just few controls. The same would go for a color image accept I will be selecting a hue or range small range of hues specific to that image. The strobe effect was self generating. Take the plasma or noise image for example that they change noise patterns on every frame. Isn't that a self generating algorithm under the hood. So I would figure that a strobe node can do the same thing with more color control.

**Comment by devernay** [comment]
but what does it look like? do you have any example around?

**Comment by blackearth2014** [comment]
I will try to find something that may help but its going to take a while.

**Comment by olear** [comment]
I need at least something to compare against ;) (no rush on the material)

**Comment by blackearth2014** [comment]
I have no need for this dedicated effect. I can simulated this in a group node.
