### ISSUE TITLE
Implode Node: Enhancement

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#177]
I am using the implode node factor at around -2.70 to get a tornado eye of the storm effect. See attached image. I was wondering if a rotation factor can be added as well. I tried experimenting using the transform mask node to no avail. If it is possible. can it be implemented by v2.1.

Thanks

![polar_eyestorms](https://cloud.githubusercontent.com/assets/7956901/9842929/ef2914b4-5a82-11e5-962f-c87cace45c5a.png)

**Comment by olear** [comment]
Ok, will see what I can do.

**Comment by blackearth2014** [comment]
No rush, Thanks.

**Comment by blackearth2014** [comment]
I just remembered the Swirl Node. If that node feature can be implemented as a rotation factor just processing the implode factor using negative values, that could be awesome.

**Comment by olear** [comment]
So, just add the 'swirl' function from Swirl.ofx in Implode.ofx? Should swirl be applied before or after implode? (or an option?)

**Comment by blackearth2014** [comment]
The swirl should be an option to be able to be before and after the implode. It's always about the options.

**Comment by blackearth2014** [comment]
Is it possible to implement some of the resize nodes filters into the swirl and implode nodes? Will they have any effect on them at sub pixel values? Will they be able to give that silky-milky look. I know that it is a crazy non-existent description, but I am just curious.

![implode and swirl filters](https://cloud.githubusercontent.com/assets/7956901/10873160/e78b6578-80dd-11e5-952a-dacecc70ae98.png)

**Comment by blackearth2014** [comment]
You know what will be cool if a drawn bezier curve from the roto node act as a Lathing tool for the Swirl or Implode. I know this will require research or and cray math. What I mean by lathing is the rotoshapes or bezier curves are used as smoothing & warping guides in the ROI. Its something like the bilateral guide node which effect is guided by a luminance map.

**Comment by devernay** [comment]
@blackearth2014 @olear if we have the mathematical formula for the transform, it's very easy to implement it in openfx-misc directly (just like the Distortion node), and it will benefit from the supersampling filters I did
