### ISSUE TITLE
Bubble Text Generator Node: Request

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#178]
Olear,

I have a strange node request. I am in the midst of recording and editing a short film to be entered into a iPhone Film Festival. My dead line is Dec 19, 2015. The images below are something that I would like a node to generate with ability to put text in it and animate at times on the timeline.. There will be a couple of scenes where I am filming a conversation between two Canadian Geese discussing geese population politics. I need to track those bubbles in with the text displaying what they are discussing.

Another idea is to create another TextOFX node that will allow me to use images below as mask and text border margins. The text will auto wrap based on the mask borders.

![orange-speech-bubble-512](https://cloud.githubusercontent.com/assets/7956901/9925454/b13993e6-5cd9-11e5-9569-69453fbc6058.jpg)

![016979-3d-transparent-glass-icon-symbols-shapes-thought-bubble1-sc37](https://cloud.githubusercontent.com/assets/7956901/9925453/b1390980-5cd9-11e5-828a-568223e7554a.png)

**Comment by olear** [comment]
I don't think a new node is needed ....

You can use the 'canvas' feature in TextOFX to adjust the text "box" and set gravity to center forced, then use transform to position the text, like:
![snapshot1](https://cloud.githubusercontent.com/assets/7461595/9949783/1e52e332-5db2-11e5-803a-1607fb661173.png)

Note that TextPango is probably a better alternative, since you have more control (aligment etc):
![snapshot2](https://cloud.githubusercontent.com/assets/7461595/9949797/4bfe60cc-5db2-11e5-81da-13030cc62e5a.png)

**Comment by blackearth2014** [comment]
I will give it a try. TextPango still doesn't work on the my Mac though.

**Comment by olear** [comment]
I though mac issues was resolved ... crash or no fonts?

**Comment by blackearth2014** [comment]
No Fonts. The recent Mac builds has been crashing on launch. Fred replied that there were issues with Mac's deployment and should be fixed in a couple of days, hopefully.

**Comment by olear** [comment]
The font issues should be resolved, but if you get no fonts then there are still issues... (never-ending story it seems)

Anyway, test TextOFX and see if that helps, I can maybe adjust some thing in TextOFX if you need, but advanced text handling is TextPango's domain.

**Comment by blackearth2014** [comment]
By the way, Love the TextOFX node. If possible, can the Text Direction operator get a justified option for those paragraphs overlays.

Thanks

**Comment by MrKepzie** [comment]
The mac build will be fixed soon, we have compiler issues, they will be solved soon

**Comment by olear** [comment]
@blackearth2014 text wrapping can not be added to TextOFX at the moment, but TextPango has the features you want (when it works on Mac).
