### ISSUE TITLE
abort render

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#179]
Make it possible to abort the render.

**Comment by olear** [comment]
Not easy, all I can do at the moment is to set a time limit. Will check more ...

**Comment by olear** [comment]
I can't stop/abort running IM "functions"... The best I can do is add abort before/after IM functions in the render.

**Comment by devernay** [comment]
which is why we have to work on the gmic meta-plugin! (David made most CImg/gmic functions abortable for us)

**Comment by olear** [comment]
yeah.... I just don't have much experience with cimg/gmic, but will learn ;)
