### ISSUE TITLE
Merge Text(Pango)+Read(SVG/PSD) with OpenFX-IO?

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#180]
Merge Text(Pango)+Read(SVG/PSD) with OpenFX-IO?

Pros:
- Everything is in one repo
- All depends are in one bundle
- can be maintained by more people
- openfx-arena will only depend on (a stripped down) IM (no added depends needed)

Cons:
- added depends/build proc for OpenFX-IO (but we do it anyway through arena)

**Comment by devernay** [comment]
There may be license issues with IM and/or its dependencies, we have to be careful about that, especially if we bundle these plugins with openfx-io.
I don't understand the IM license very well. Is it LGPL-like or GPL-like? FSF declared it non compatible with GPLv2, but compatible with GPLv3.

TextOFX/TextPango: it would be nice to remove the dependency on IM, and use freetype/pango (or maybe just pango) directly, thus getting rid of licensing issues.

ReadSVG: depend directly on librsvg?

ReadPSD: ??? is the rendering code in IM or in one of its dependencies?

**Comment by olear** [comment]
IM is BSD/Apache with attribution (powered by imagemagick or something), so I don't see any problems with that(?)

TextOFX is pure IM (but need freetype/fontconfig+libpng)
TextPango: uses IM as a wrapper against Pango (IM takes care of everything and return a bitmap from pango)
ReadSVG: same as Pango (but also handles text/font)
ReadPSD: pure IM (but uses lcms for color convert), and some custom code from me against lcms

**Comment by devernay** [comment]
There seems to be no problem with the license, except that we have to respect the attribution clause, and...
 * include a copy of the license in any redistribution you may make that includes ImageMagick software
(I just reminded @MrKepzie that we still don't include the licences with the natron binaries)

However, my experience with IM is that it's  large, clumsy and buggy. Could we just extract the required components?

**Comment by olear** [comment]
The IM license are included on both Win and Lin.

I currently have a fork where i'm stripping away unneeded stuff. My experience is that Text* and Read* are stable against IM 6.8.10-1 (my mod) .

I have already merged the plugins in IO just to test.

**Comment by devernay** [comment]
There seems to be a license issue: RSVG is GPL, and IM uses RSVG (or at least links to it).
We should thus probably:
* reimplement TextOFX without IM
* distribute the rest of openfx-arena separately

**Comment by devernay** [comment]
Of course, openfx-arena can still be bundled with GPL Natron

**Comment by olear** [comment]
the library in librsvg is lgpl.

**Comment by olear** [comment]
Too close to release to consider merge, keep as-is until now.
