### ISSUE TITLE
ReadSVG node: multi-layer splines or objects extraction.

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#182]
Is it possible to optimize the ReadSVG node to read & extract layers and objects from an SVG file created by Inkscape.

The reason I asked is because the SVG file can be more portable between Natron productions instead of having to go in and out Inkscape if you need to move an object.

**Comment by olear** [comment]
If I'm not mistaken librsvg only return a bitmap of everything, will check.

**Comment by olear** [comment]
Nope, not possible (easy way to check is to load an SVG through ReadPSD).

The only way this is possible is to parse the XML/SVG and split out any layers etc into new XML's and then convert each XML to bitmap.

**Comment by olear** [comment]
So in other words, not possible with current ReadSVG, but maybe in the future (will probably require a complete rewrite without IM).

**Comment by blackearth2014** [comment]
Cool Breeze
