### ISSUE TITLE
Modulate Plugin: Mask Component

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#183]
Olear,

Your Modulate node doesn't have a Mask input like your other nodes in the OpenFX-Arena category. Is it possible to get it.

**Comment by olear** [comment]
Shouldn't be a problem (not tested, but will), the plugin was made by request, so I just added what was needed at that time.

Was a bit unsure about adding it to the bundle due to the amount of existing color nodes.

**Comment by blackearth2014** [comment]
I understand, but your node processes a little different look when adjusting its parameters. You can get extreme when little effect. My ideology is that if the node can inspire creativity from a different perspective, then that node is worth having.

**Comment by blackearth2014** [comment]
Thanks
