### ISSUE TITLE
Arch Node: Mask Input Crashes Natron

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#184]
The Arch node works fine until I attached a RotoPaint node to the mask input and it crashed Natron.

**Comment by olear** [comment]
Don't crash here...
![snapshot5](https://cloud.githubusercontent.com/assets/7461595/10120873/8174525e-64d1-11e5-802d-ae32e41cc217.png)

What build are you on?

**Comment by blackearth2014** [comment]
I am on a Mac. I am about to download the latest snapshot.

**Comment by MrKepzie** [comment]
Fixed
