### ISSUE TITLE
Font Types view: Feature Request

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#189]
It is possible to be able to see what the Font Type will look like prior to selecting it and waiting for it to appear in the viewer. I have over 200 fonts in my Mac font boot. Is it possible to cache the fonts and fonts visuals.

Also is it possible to have a preference feature to create favorites for which fonts you use the most and it shows up in the font drop down menu in the plugin. Better yet, is it possible to scan the fonts to see if their meta data has a category feature baked in. Some fonts will be better for web, print, fun, sci-fi, horror and traditional. It will be nice if these could be categorized like this.

![fonts viewer](https://cloud.githubusercontent.com/assets/7956901/10474758/949902aa-7208-11e5-8554-a64053ec55e9.png)

**Comment by devernay** [comment]
I think the Font Book (which you're showing) is a nice utility that fullfils that purpose.
Would integrating it into Natron really be useful when there is a separate utility for this?

**Comment by blackearth2014** [comment]
I believe so. I would have to have both apps opened and flipping back and forth to see what the font looks like. Gimp and Krita allows you to see what the font looks like why working in the app. I have Nuke 6 and I know that it doesn't have this feature. I can't speak for the later versions but I truly think it will help speed up text motion graphics by 25%.

**Comment by olear** [comment]
Preview of fonts in list is not possible, and requires modifications to Natron, OpenFX and TextOFX.

I can add a boolean 'preview' param that can show a font preview (IM can load ttf as image) in viewer. But if it has any use is another thing ...(?)

**Comment by blackearth2014** [comment]
Okay, cool breeze
