### ISSUE TITLE
Range Selector and Properties: Feature Request

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#190]
Could we get a range selector with properties for your PangoCairo development. This video link explains what I mean at https://youtu.be/o1h97XYUByo.

**Comment by olear** [comment]
You want each letter to fade in?

Set a span with font size on each letter, then animate the size(?)

**Comment by olear** [comment]
TextPango is EOL (no more features, still supported), will be replaced by a new text node (Natron 2.2~3.0).

**Comment by blackearth2014** [comment]
Cool Breeze
