### ISSUE TITLE
[spherize] there is imagemagick, this is true needed!

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#191]
hello
there is spherize from imagemagick, so you can create new without problem, :-)
then link:
http://www.imagemagick.org/Usage/mapping/#spherical

script from fred's :
http://www.fmwconcepts.com/imagemagick/spherize/index.php

do you can create new node?
thank you

**Comment by manuelsongokuh** [comment]
see other example from ADOBE PHOTOSHOP:
![link](https://cms-assets.tutsplus.com/uploads/users/723/posts/24925/image/space3-2a.jpg)

**Comment by manuelsongokuh** [comment]
thank you!

**Comment by olear** [comment]
This should be possible with the new GMIC plugins.
