### ISSUE TITLE
Context-dependent choice menus

### ISSUE THREAD

**Issue by devernay** [olear/openfx-arena#194]
if the user installs or uninstalls fonts, the "fontName" param (which is the index in the list of available fonts) does not point to the same font.
the text plugin should set the "fontOverride" value in changedParam() when changing the "fontName" choice menu, and use the value from fontOverride and not the value from fontName when rendering.

To synchronize fontOverride with fontName when loading a project, this can be done in the plugin constructor:
```
    // setValue() may be called from createInstance, according to
    // http://openfx.sourceforge.net/Documentation/1.3/ofxProgrammingReference.html#SettingParams
```
- if fontOverride is empty (loading an old project), set it to fontName
- if not, and fontName points to a different font, set fontName to the correct index

See how it works in openfx-io/IOSupport/GenericOCIO.cpp for example.

**Comment by devernay** [comment]
I made an explanation on how to fix this on https://github.com/MrKepzie/Natron/wiki/OpenFX-plugin-programming-guide-%28Advanced-issues%29

**Comment by olear** [comment]
Thanks, will fix.

**Comment by olear** [comment]
Must also be done in ReadPSD (lcms profiles).
