### ISSUE TITLE
Test on Mac

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#2]
Test and build plugin on Mac (OS X).

**Comment by olear** [comment]
Wil make a "universal" build script, so should be easy for anyone with a Mac to adapt and build.

**Comment by devernay** [comment]
I'll work on this one.
The difficult part is to find out where to install the imagemagick plugins. The path has to be hard-coded in the source code (in applications, that path can be relative to the binary, but not in dylibs, AFAIK).
I propose to put everything (dylibs and OFX plugins) in /opt/openfx-arena (as I did for TuttleOFX on OS X), would that be satisfactory ?

**Comment by olear** [comment]
Didn't notice your post before now.

Note sure I understand (not a Mac user), but can't you just build ImageMagick, libpng and zlib (I guess fontconfig+freetype is present on Mac) as a static libs, then link against them? See deploy.sh for more information.

But as long as the plugin(s) work, where they are is not important(?).

Note that only the Text plugin is stable (cd Text;make) yet.

**Comment by olear** [comment]
Will be fixed when/if included in Natron.
