### ISSUE TITLE
ReadPSD: implement onInputFileChanged

### ISSUE THREAD

**Issue by devernay** [olear/openfx-arena#200]
When building snapshots (which use the latest openfx-io):
```
../OpenFX-IO/IOSupport/GenericReader.h:149:18: note: unimplemented pure virtual method 'onInputFileChanged' in 'ReadPSDPlugin'
    virtual void onInputFileChanged(const std::string& newFile,
```
look in readers of a reasonable implementation. All you have to do is set the default colorspace to a reasonable value (it may depend on the file content).

**Comment by olear** [comment]
I updated IO, and adapted, but I never got an image, so I reverted the change.

**Comment by devernay** [comment]
The function could even be empty (but should not be)
Any idea why you don't get an image?
In the mean time snapshots don't compile
Le 31 oct. 2015 20:10, "Ole-André Rodlie" <notifications@github.com> a
écrit :

**Comment by devernay** [comment]
I temporarily disactivated pulling out the latest version of submodules for openfx-arena.

**Comment by olear** [comment]
Just got home, will update code shortly.
