### ISSUE TITLE
compilation issue: libgomp

### ISSUE THREAD

**Issue by devernay** [olear/openfx-arena#201]
libgomp is only available on gcc, and only necessary if ImageMagick was compiled with OpenMP support:
```
Makefile.master:53:  MAGICK_LINKFLAGS += -lgomp -lm -lpthread
Makefile.master:54:  GMAGICK_LINKFLAGS += -lgomp -lm -lpthread
```
is there a way to check if Magick was compiled with OMP and only append -lgomp in this case?

**Comment by devernay** [comment]
In the mean time, I added the following to the OSX build script:
```
echo "Warning: removing -lgomp from MAGICK_LINKFLAGS, since ImageMagick on OSX is compiled without OMP support"
sed -e s/-lgomp// -i.orig Makefile.master
```

**Comment by olear** [comment]
Will add a check.

**Comment by olear** [comment]
should work with latest commit
