### ISSUE TITLE
Transform Overlays for Distortion effects: Swirl & Implode

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#204]
Olear,

Can you implement a transform overlay for the Swirl and Implode node. This way I can animate where the may effect the image.

**Comment by devernay** [comment]
@blackearth2014 what exactly should the transform do:
- select where the effect shoud happen, i.e. the equivalent of inverse transform, followed by distortion, followed by transform
- transform the result, i.e. the equivalent of distortion, followed by transform
?

@olear Someone (me?you?) has to take a bit of time to dig out the mathematical formula for each of these geometric transforms. then we can implement these as simple plugins that don't depend on IM (see Distortion in openfx-misc), with exactly the same set of parameters, and we can even easily add a "Transform" tab to implement this feature request (I'm waiting for @blackearth2014 to know what the transform should do).

**Comment by blackearth2014** [comment]
I want to be able to move the effect to where it should happen on the image. The effect defaults to the center of the image, but I want to animate that effect at different coordinates or places within the projects resolution.

**Comment by olear** [comment]
Known feature request (for swirl/implode), but not possible without modifying IM or get the devs at IM to add the feature. Will have a quick look at the source.

As @devernay said it would be best to move the distorts to openfx-misc, but that may take a while.

**Comment by olear** [comment]
Got it working (on swirl) ...
![new-swirl](https://cloud.githubusercontent.com/assets/7461595/11162695/5ddca9a6-8aae-11e5-866a-6e59d1ac6212.png)

Required several changes to IM, but it works for our plugin (not upstream quality). Will try to see if implode is as simple to hack.

**Comment by blackearth2014** [comment]
This what I was asking for. A simple position option. Great Thanks.

**Comment by olear** [comment]
Not a 100% what you want, since you can only adjust effect centre, so it won't be a proper transform. But better than before ...

IM patch must be integrated with build servers before a build will be available.
