### ISSUE TITLE
Edge node: Noise influenced

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#205]
Is it possible to have the SeNoise node noise type implemented in to the Edge node to generate edges based off the noise type? Still have the controls to adjust the noise type to generate different edge patterns.

![noise - edge node](https://cloud.githubusercontent.com/assets/7956901/11109681/0ed1261e-88c1-11e5-9238-6071fd030dce.png)

**Comment by MrKepzie** [comment]
We will soon add these noises to the Python API of Natron, so then it's just a matter of setting an expression of the corresponding parameter. No need to add SeExpr to openfx-arena.

**Comment by devernay** [comment]
I don't understand what you mean, @blackearth2014 , by "generate edges based off the noise type" ?
If it's an image processing thing, I doubt it has something to do with adding noise to the python API.

**Comment by devernay** [comment]
Can this issue be reopen, please?

**Comment by blackearth2014** [comment]
What I mean @devernay @MrKepzie @olear , If you look at the attached picture, the lines are all the same even with the smooth. I just watch to know if the noise like turbulence or fbm can influence a different line shape or shape patterns on an image edge contours.

![edge node](https://cloud.githubusercontent.com/assets/7956901/11116614/c1b2c52c-8901-11e5-9dd0-f29314499e66.png)

**Comment by devernay** [comment]
Isn't it just a matter of adding SeNoise between Read and Edges?
The lines are not the same, notice how the beard disappeared because it contains edges smaller than the smoothing parameter.
