### ISSUE TITLE
Is possible: white balance point plug-in?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#211]
hello

Is possible, add new little plug-in: white balance point? 
this 'white balance point' is powerfully, usefully full to all software: NLEs, COMPOSITEs..
in blender will be new feature next version go to see news:
https://plus.google.com/+PlasmasolutionsDe/posts/UKjEcdAusx1

white balance point is simple to use it: a video footage error color (yello or orange) grab point of colore to convert in white this operation is balance RGB to new RGB..
this is true powerfully and usefully..

there are many information helpfully for you:
https://en.wikipedia.org/wiki/White_point
http://www.astropix.com/HTML/I_ASTROP/CUSTOMWB.HTM
http://www.comp.nus.edu.sg/~brown/pdf/ColorConstancyJOSAv10.pdf

programming code:
http://web.stanford.edu/~sujason/ColorBalancing/simplestcb.html
https://gist.github.com/tomykaira/94472e9f4921ec2cf582
http://docs.opencv.org/3.0-last-rst/modules/xphoto/doc/whitebalance.html
https://eternalwandering777.wordpress.com/2012/12/16/automatic-white-balance-algorithm-1/

![example error color of white](https://cdn.tutsplus.com/photo/uploads/legacy/103_whitebalance/4.jpg)

for command imagemagick 
http://fmwconcepts.com/imagemagick/whitebalance/index.php

but that all is automatic white balance, but not POINT handle (picker) like as all NLEs, COMPOSITEs..

is could be 2 plug-in:
1. plugin 'automatic white balance'
2. plugin 'white balance point'

is this good idea for new feature for openfx-arena?

maybe use from imagemagick or openCV

**Comment by sozap** [comment]
Hum, I think the grade node already does that...
Black Point helps to set the darkest part of the image to pure black
and White Point set the brightest to white...
It's true that's not automatic
