### ISSUE TITLE
Krita Document Support (ReadKRA)

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#213]
Similar to OpenRaster ... Also add anim support when stable in Krita (https://github.com/MrKepzie/Natron/issues/1109)

**Comment by olear** [comment]
added v1, reads the image. v2 will have multiplane.

**Comment by olear** [comment]
Due to undocumented binary format for the layers this plugin will not get any more features, I will probably just merge this plugin into ReadORA, or remove it.

**Comment by boudewijnrempt** [comment]
Yes... Honestly, we're sort of in the same situation as the gimp people with xcf: it's an internal format, and we suck at documenting it even more than the xcf documentation. Though that is more accidental than intentional, and we _should_ have documented it, or be documenting it.

**Comment by olear** [comment]
Will have a look at your code and see what I can do, currently not high on my priority's. We are able to view the merged image in Natron, and at the moment this is what most people want, a quick edit in krita and a quick reload in Natron.

Thanks for taking your time to comment on this.
