### ISSUE TITLE
Particle engine.

### ISSUE THREAD

**Issue by Ambassy** [olear/openfx-arena#214]

**Comment by Ambassy** [comment]
I have once seen your post showing particles generated in natron using  the seExpression node in natron. If my brain didn't fail some body said the particle node can be written from that expression. Can you please write that node in your arena bundle? We need it with natron even if it can be very basic particles. Thanks for your time.

**Comment by olear** [comment]
I used the PovRay node to create a basic particle engine, but It wasn't fast. I can see what I can do, but I may be beyond me to create something from scratch...

**Comment by Ambassy** [comment]
Yes the POVray. No blame  on you to what you are not able to do, cause none who knows all. You deserve my gratitude.

**Comment by olear** [comment]
Possible with Shadertoy in openfx-misc.
