### ISSUE TITLE
why did removed rotate for polar?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#219]
hi

i wish to know why did removed the rotate for polar? i need this..

**Comment by olear** [comment]
Well, it never actually worked properly, the rotate was wrong compared to how it worked in Arc (as it should be). I also have some issues with the distort function in ImageMagick (resample assert), and the rotate function did sometimes trigger that.

You can use a normal transform? Or better yet use the Arc node, it has proper rotate.

**Comment by manuelsongokuh** [comment]
hi

i use so much polar with rotate, instead trasform node is connect all size, instead polar with rotate is not connect all size , htat is connect to circle (polar)this is correct rotating..
maybe find other solution for issues fix.. 

if you remove rotate to polar so in fact the lose functional against to AE.. because AE has rotate for polar.. 

i respect you for your choice ..
node transform is philosophy for Natron base. polar with rotate best to use it "ready"..

**Comment by olear** [comment]
Ok, if the node don't trigger any crashes in ImageMagick, I will re-add.

**Comment by manuelsongokuh** [comment]
ok, thank you but not forget it ok? thank you
