### ISSUE TITLE
ReadXCF (and possible ReadPSD and ReadSVG)

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#22]
Try to make a image read node, this will add support for XCF and others not supported by OIIO.

**Comment by olear** [comment]
fork IO and do it there.

**Comment by devernay** [comment]
I'd rather see that in IO. That way, all bundled libraries wouldn't be duplicated.

**Comment by olear** [comment]
Yepp, will test here first, then "port" to IO.

Will consentrate on XCF and layers.

**Comment by olear** [comment]
Got an semi working read node, getFrameBounds works, but the decode function does not seems to work (no code in that function seems to run). Probably a stupid error on my part, but getting there.

Will keep the plugin in the Arena bundle for now (added openfx-io as an submodule to get the IOSupport).

**Comment by olear** [comment]
![screenshot-9](https://cloud.githubusercontent.com/assets/7461595/8273361/568aabd2-186a-11e5-9693-a03526ffb477.png)

Got a basic version in trunk. May need some error checking, and I need to add support for layers.
