### ISSUE TITLE
Rewrite SVG-based plugin(s)

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#220]
Hit an issue with ImageMagick on Windows. I can't read Blobs containing SVGs (Windows-only issue), this creates some issues for future enhancements to the current plugin(s). So, modify the plugin(s) to use librsvg+cairo directly.

**Comment by olear** [comment]
Done in trunk. Got a big performance increase as a bonus.

**Comment by devernay** [comment]
super!
