### ISSUE TITLE
Port Magick.ofx to ImageMagick 7

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#234]
After Natron 2.1, move to IM7.

**Comment by olear** [comment]
So.... Did a quick test.

Most plugins use 'matte' and 'CopyOpacityCompositeOp', these have now been replaced with 'alpha' and 'CopyAlphaCompositeOp', trivial to fix.

Edges uses 'quantumOperator', this function does not exists anymore, I need to find the "new" function for this. 

The 'draw' function does not accept 'std::list' anymore, this completely breaks the Text plugin (but by the time 2.2 is out this plugin should be removed anyway?).

And probably more ...

**Comment by olear** [comment]
done in IM7 branch. Note that this breaks IM6. Should I merge this for Natron 2.1 or wait?

**Comment by devernay** [comment]
better wait (on osx, both macports and homebrew are still at 6.9)

**Comment by olear** [comment]
They will probably be on v6 for a very long time, there should be no problems making a v7 portfile, as they don't conflict.
