### ISSUE TITLE
Edges node: add a threshold parameter (enhancement request)

### ISSUE THREAD

**Issue by nicholascarroll** [olear/openfx-arena#235]
Can you add a 'threshold' parameter to the Edges node, so that the user can adjust that to isolate the edge lines?

Also, is this using canny method? 
http://www.imagemagick.org/Usage/transform/#canny

**Comment by olear** [comment]
Will check.

I'm using http://www.imagemagick.org/Usage/convolve/#edgedet

**Comment by olear** [comment]
There will be a new edge node in Natron 2.1.8 through openfx-misc. Since that will have more features and is faster I will deprecate 'Edges' in Natron 2.2, and move the plugin to openfx-community (that also have a CannyEdge node).
