### ISSUE TITLE
Unable to navigate all fonts (in Natron)

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#24]
Hi,
Thanks for the works.. But i can't test it.

If i install from binaries https://github.com/olear/openfx-arena/releases/download/MagickText-v1.0/Text.ofx.bundle-1.0-Linux-x86-release-64.tgz , it doesn't appear in the natron tools (text.bundle is installed in /usr/OFX/Plugins).

So, I try to compile it and here  :

$ make -C Plugin
make[1]: Entering directory `/home/rapha/SOURCE/openfx-arena-MagickText-v1.0/Plugin'
../Makefile.master:6: ../OpenFX/Support/Plugins/Makefile.master: No such file or directory
make[1]: *** No rule to make target `../OpenFX/Support/Plugins/Makefile.master'.  Stop.
make[1]: Leaving directory `/home/rapha/SOURCE/openfx-arena-MagickText-v1.0/Plugin'
make: *** [Plugin] Error 2

What's happened ?

**Comment by olear** [comment]
Binary should work.

Please post output of /usr/OFX/Plugins/Text.ofx.bundle.

See README.md for building from source. You need to update submodules.

```
git submodule update -i
cd Text
make
```

**Comment by rcspam** [comment]
output of /usr/OFX/Plugins/Text.ofx.bundle ?

$ ls -lR /usr/OFX/Plugins/Text.ofx.bundle
/usr/OFX/Plugins/Text.ofx.bundle:
total 4
drwxr-xr-x 4 rapha rapha 4096 mai    1 06:41 Contents

/usr/OFX/Plugins/Text.ofx.bundle/Contents:
total 12
-rw-r--r-- 1 rapha rapha  579 mai    1 06:41 Info.plist
drwxr-xr-x 2 rapha rapha 4096 mai    1 06:41 Linux-x86-64
drwxr-xr-x 2 rapha rapha 4096 mai    1 06:41 Resources

/usr/OFX/Plugins/Text.ofx.bundle/Contents/Linux-x86-64:
total 4716
-rwxr-xr-x 1 rapha rapha 4827464 mai    1 06:41 Text.ofx

/usr/OFX/Plugins/Text.ofx.bundle/Contents/Resources:
total 8
-rw-r--r-- 1 rapha rapha 2878 mai    1 06:41 net.fxarena.openfx.MagickText.png
-rw-r--r-- 1 rapha rapha 2769 mai    1 06:41 net.fxarena.openfx.MagickText.svg

**Comment by olear** [comment]
Looks ok.

```
ldd /usr/OFX/Plugins/Text.ofx.bundle/Contents/Linux-x86-64/Text.ofx
```
Any 'not found' ?

What distro are you using?

**Comment by rcspam** [comment]
ubuntu 14.04

**Comment by rcspam** [comment]
Ok i'm not searching in the right place tools.
Text appear in I/O tools not in Draw tools.
Thanks to your screenshot... ;)

... And compile are OK now !!

Thank you.
Rcspam

PS: Not yet solutions for https://github.com/MrKepzie/Natron/issues/509# Natron issue ?

**Comment by olear** [comment]
The binary should work on any Linux distro released since 2007, a bit strange if it didn't work on Ubuntu :)

Will look into #509, forgot about it.

**Comment by rcspam** [comment]
Olear,
Another little problem, i have many fonts, it impossible to navigate if number of fonts is importante and fill the screen. But it's probably an Natron issue..
![natron - untitled ntp - _001](https://cloud.githubusercontent.com/assets/10021906/7428115/7c382c40-efea-11e4-99bb-33f360d977ef.png)

**Comment by olear** [comment]
Yeah, that's a Natron issue. Also https://github.com/MrKepzie/Natron/issues/311

I could add a manual font option, since all fonts are a bit hard to find in Natron at the moment. Will also try to find the bug in Natron.

**Comment by rcspam** [comment]
Ok, great job
Cu

**Comment by olear** [comment]
fixed upstream
https://github.com/MrKepzie/Natron/commit/dc61ae34e36e6adc576e84edf503896dcd21d2ba
