### ISSUE TITLE
TextFX: cairo-win32-font threading issues

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#242]
Get very strange issues during playback in Natron on Windows. Get a bunch of Pango and Cairo warnings and errors, and the text rendering fails, but if I write the animation out to disk everything is just fine, or I manually just step the frames, only happens on playback. 

Have built many different versions of Pango, and the issue still remains, also tried several things in the plugin without any luck. Only happens on Windows during playback.

Tested 2.0.x and 2.1.

On a semi-related note, this is also what gives an assert in Magick-based plugins with OpenMP during playback, works fine on write-to-disk, though that issue is present on all platforms.

**Comment by olear** [comment]
Works fine in Catalyst Edit on Windows.

**Comment by olear** [comment]
The issue is triggered by "auto size".

**Comment by MrKepzie** [comment]
This is a multi-threading issue, your plug-in probably does not support multi-threading correctly and crashes.
just run it through gdb in debug mode and get a backtrace

**Comment by olear** [comment]
Seems cairo-win32-font has threading issues. Found some old patches I will try to get working, if not the "auto-size" feature must be disabled at least on Windows until this has been fixed upstream (Cairo).

> I had encountered a multi-thread issue in cairo-win32-font.c line 133 to line
153 (_get_global_font_dc()). There is a static variable in this function and
when two threas are rendering the text. Although they dosen't share any cairo_t*
or cairo_surface_t* it will end up failing the cairo rendering because of this
static variable.

https://bugs.freedesktop.org/show_bug.cgi?id=73012
http://marc.info/?l=cairo-bugs&m=138787771209413&w=2
