### ISSUE TITLE
TextFX: Add font color in Markup

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#245]
The attributes that are working in the TextPango node does not work in the TextFX node with the markup button enabled and vice versa.

**Comment by olear** [comment]
The only thing not working in markup (as far as I know) is color, will try to enable. Has been broken since I changed how the text is rendered.

**Comment by blackearth2014** [comment]
Dude, I was racking my brains over that. 

Cool Breeze.

**Comment by olear** [comment]
The reason for this is that I convert the text to path before rendering, and color information is the lost. I made the change due to antialias issues on Windows, will try to find a fix.

**Comment by olear** [comment]
So, I re-added color support, but only for Linux and Mac. I currently don't have a fix for Windows yet.

**Comment by blackearth2014** [comment]
This may sound like a crazy idea or implementation. What if you add a way to only pass a word, character or phrase to pass as new alpha channel in the node that can be piped into solid color, hvstool or colorlookup node for hue coloring. For example, using a format like double strike through to indicate that the word, character or phrase are to pass only as a new alpha output. Then use a merge node to combine the changes while the new alpha output channel operates as a mask input to the color nodes.

Now that I think of it. It's more work than necessary for a simple fix, but interesting nonetheless.

**Comment by olear** [comment]
I will find a fix eventually, my biggest issue is that Cairo uses the native font api on Windows, and it's subpixel-idiocracy overrides what I want (proper looking text).

**Comment by olear** [comment]
Close for now, works on Mac and Linux. Will enable on Windows when/if I can fix the subpixel stuff.
