### ISSUE TITLE
Project Alignment Node

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#246]
Ole,

After the feature freeze is over for Natron 2.1, can you modify the Switch Node to act as a project switch alignment node? For example, I need a node that will allow me to connect multiple ReadOIIO nodes to it and the node will automatically divide the screen into parts displaying images connected to it.

The attached image below is a screenshot comp that I did with a gimp file that was already pre-laid out. I just want something with random connectivity. It has to be aware of the project settings resolution. If the project is an HD format, then the node will divide the viewer to the number of connected images. It doesn't have to scale the images. A connect Transform node will do all of that.

![alignment node](https://cloud.githubusercontent.com/assets/7956901/15970908/2094ae62-2f05-11e6-9a1c-e8e32e94bcff.png)

Thanks

**Comment by devernay** [comment]
Do you need something that allows you to preview the inputs before selecting one? I could do this: a checkbox in the switch node would enable a special mode where you see a mosaic of the inputs, and you could just click one to set a keyframe (this would highlight the selected input in the mosaic). Then you would have to uncheck the checkbox to get back to normal. I could do the same in the dissolve node.
This would be for 2.2. Please post an issue on the Natron github if that's what you want.

Note that in the graph above you could use a single merge node and connect the background to B, and all the input layers to A1, A2, A3, etc.

**Comment by blackearth2014** [comment]
That is right. The merge node is a better choice for this operation but with this new feature operation. In this case, B input will be a solid black and then just keep adding the to the A inputs. Once all of my images are connected, I would be able to click a checkbox in the merge node to auto fit or divide the project settings resolution were all the image can be displayed on the screen. Like I posted early, this feature doesn't reformat the connect images to the project's resolution. That should be for the artist to adjust with the transform node before each image input.

This feature is like Nuke's contact sheet node but with more flexibility. The switch node mosaic feature is not necessary for my specific request now that I have thought about more, but I do find it useful.

Thanks Fred

**Comment by olear** [comment]
Not an openfx-arena issue, close.

**Comment by blackearth2014** [comment]
Is there a way to push this into the main issue without having to copy and paste everything.

**Comment by olear** [comment]
Not that I'm aware of, you can always reference this issue (but you still have to write subject and description):

```
https://github.com/olear/openfx-arena/issues/246
```
