### ISSUE TITLE
ReadSVG/KRA/ORA/PSD Node: Graphics not appearing

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#250]
In the latest Master snapshot (Natron-201606271419-64081d7ff2999c03102aca2246eee0d71dadd2c8), the ReadSVG/KRA/ORA/PSD nodes are not displaying the color.rgb/alpha graphics. The layers, paths, and groups id names appear, but not the graphics themselves.

**Comment by olear** [comment]
fixed in d69702c5aee536cc7caa368c40efe283c7337e2c
