### ISSUE TITLE
TextFX Node: Error not loading

### ISSUE THREAD

**Issue by blackearth2014** [olear/openfx-arena#251]
Here is what I see in the Draw Menu.
![textfx menu](https://cloud.githubusercontent.com/assets/7956901/16418612/a5752ab4-3d18-11e6-9582-aec2a12d4589.png)

This is what I get with both the TextFX and TextFX 1 nodes.

![textfx - error](https://cloud.githubusercontent.com/assets/7956901/16418638/bfbd61de-3d18-11e6-9d1f-e6fbe6a4d26b.png)
![textfx 1 error](https://cloud.githubusercontent.com/assets/7956901/16418639/bfcc9ef6-3d18-11e6-873a-f2e965052c34.png)

This is the latest snapshot that is not working at Natron-201606281410-3d9bfe67aae38ec5000400e60a76dc6d35951982.

**Comment by olear** [comment]
Fontconfig is broken/missing on the Mac builds it seems, affects TextOFX, TextFX and Polaroid.

**Comment by olear** [comment]
Will be fixed in next snapshot.
