### ISSUE TITLE
Text: ChoiceParam use string not int

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#26]
Is it possible to get the string value from OFX::ChoiceParam? Using int's on fonts is not the best solution if/when your font collection changes. Sharing projects with fonts will not work.

**Comment by olear** [comment]
Can't find any info regarding strings and OFX::ChoiceParam. Can I only get the int value? not the label?

Without the label I'm a bit lost on solving this issue.

**Comment by olear** [comment]
Workaround is to use the new 'custom font' feature in trunk.

**Comment by olear** [comment]
Missing feature in OpenFX, can't fix(?).

**Comment by MrKepzie** [comment]
The function you are looking for is 
    getOption(int,std::string&)

**Comment by olear** [comment]
Thanks, will test, didn't find any info in the spec.

**Comment by olear** [comment]
Fixed in trunk, and I need to learn to read the docs better :P
