### ISSUE TITLE
[TextFX]: is it possible: effect typewriter?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#267]
hi
is it possible: effect typewriter?

**Comment by olear** [comment]
Could you explain a bit more what you expected from this kind of effect?

**Comment by manuelsongokuh** [comment]
Ok see example from Adobe aftereffect:
https://m.youtube.com/watch?v=EoNIN0onunc&time_continue=33

**Comment by olear** [comment]
Just keyframe the text.

**Comment by manuelsongokuh** [comment]
i try but not understand where i will start to try typewriter..?

**Comment by olear** [comment]
http://fxarena.net/olear/textfx.ogv

**Comment by manuelsongokuh** [comment]
ah...but is long time for add keyframe.. each letters...uhm..is not there other good fast time?

**Comment by olear** [comment]
yeah.... You could also just add a rectangle or something over the text and just slide it..... Many options, but no instant "typewriter effect".

**Comment by manuelsongokuh** [comment]
@olear so i will do in aftereffect for a piece effect typewriter, and import to natron..maybe in future hopeless..
thank you reply
