### ISSUE TITLE
RenderScale=0 Broken in latest Natron snapshot

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#39]
Don't know when or where, but Text don't work on latest workshop. I've been using a Natron build from 29 April (on Linux, can't remember what version I test against on Win, a bit newer), and didn't notice before I did a rebuild of Natron today (also tried the binary builds on SF).

Natron v1.x works, and any snapshot from early May and lower.

Text v1.0 works in latest snapshot, but not higher ...... strange

**Comment by olear** [comment]
If I enable renderscale then the plugin works, but then I get renderscale issues .......

**Comment by olear** [comment]
https://github.com/MrKepzie/Natron/commit/6f5838e2a7522e53025235a40f61c91dfdfd90dc

Is the first commit where things start to break (but the commit after works, but not the next one).

Don't have time to pinpoint direct commit at the moment, but seems to break around May the 12th.

**Comment by olear** [comment]
Affects Text and Mirror plugin. 

A bit unsure what to do, if I enable renderscale then the plugins works on Natron, but the scale is all wrong (any version), and makes the plugins more or less useless. 

If I disable renderscale then the plugins works as they should in Natron v1, but is completely broken in v2 (builds before May seems to work).

The plugins works 100% in Nuke with or without renderscale.

**Comment by devernay** [comment]
Nuke doesn't make use of renderscale at all (everything is rendered at scale 1).
@MrKepzie can you take a look?

**Comment by olear** [comment]
Moved all plugins to renderscale=1, will watch for issues.

**Comment by olear** [comment]
Closing issue since plugins don't use renderscale=0 anymore, still an issue in Natron, but it's known.

Remember to check before Natron release.

**Comment by manuelsongokuh** [comment]
hello maybe this is changed from 1 to 0 for renderscale? see link
MrKepzie/Natron@4469248
