### ISSUE TITLE
Distort: DePolar aspect ratio

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#43]
DePolar produces wrong aspect ratio, try to fix.

http://www.imagemagick.org/Usage/distorts/#depolar

**Comment by olear** [comment]
>If you allow IM to use 'bestfit' (using the "+distort" form of the operator), then it will resize the output image so as keep the 'Radius_Max' at unity scaling, and set the width to the circumference distance of the radius midway between 'Radius_Max' and 'Radius_Min'. This essentially tries to best preserve the Aspect Ratio of the polar image, though this may produce a longer thinner image than expected. For example.
  convert polar_arctic.jpg  +distort DePolar 0  world_restored_2.jpg

**Comment by manuelsongokuh** [comment]
hello
I’m Manuel, then i think if possible:
add parameter in "controls" from tab "proprietaries":

A
"interpolation: "  "100%"  like as that you video in youtube:
https://www.youtube.com/watch?v=oYXQuSRC42w

B
(second row) "method: "    "Polar" or "De-Polar"
"polar" like as https://cdn.tutsplus.com/photo/authors/legacy/Jose%20Antunes/2012/09/19/planets05.jpg)
"De-Polar" like as http://www.imagemagick.org/Usage/distorts/flower_depolar-1.jpg

words o name "de-polar or other you can choose free ok?

**Comment by manuelsongokuh** [comment]
for "interpolation" set 50% like as from video (rect to polare calcule 50%), use maybe best: linear scroll see example here:
![scroll-linear](https://cloud.githubusercontent.com/assets/12126929/7752834/0ae6b37e-ffe2-11e4-8d1d-6cd3ed32d8f0.png)


percentage or number from 0 until 1 (for me is same 0% - 100% or 0.0 - 1.0)
ok?

**Comment by manuelsongokuh** [comment]
sorry maybe i'm wrong:
"for "interpolation" set 50% like as from video (rect to polare calcule 50%)"
same that from imagemagick:
convert rose: -virtual-pixel White -distort Arc 360  arc_rose_7.jpg" this is 100% and
50% is  "...-distort Arc 180..." right?

and add word "background color:"   [click as picker color] or APLHA ON/OFF.

please number simple: 0.0 - 0.4 - 0.8 - 1.0,  not 0.000 - 0.020 - 0.200 - 0.2000 right?

thank you

**Comment by olear** [comment]
Thanks for input, will test.

**Comment by manuelsongokuh** [comment]
i did see yout test build openfx on natron worked but i need (time and think what is best visual gui)to check for design visual for GUi ok?

**Comment by olear** [comment]
fixed in next commit
