### ISSUE TITLE
Enable OpenCL if needed

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#44]
ImageMagick supports OpenCL, but only on specific functions. Currently none of the plugins use functions that is OpenCL-enabled, but this may change in the future.

This only affect the build progress.

A bonus would be to help the ImageMagick devs enable OpenCL on functions we use!

**Comment by manuelsongokuh** [comment]
this link is possible for you?
http://www.imagemagick.org/script/opencl.php

**Comment by olear** [comment]
I know how OpenCL works in ImageMagick, no point yet since no plugins use any functions that are OpenCL accelerated.
