### ISSUE TITLE
Add Texture plugin

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#45]
hello

i'm looking for noise fractal from imagemagick: not found..
i wish like as here example picture:
![hqdefault](https://cloud.githubusercontent.com/assets/12126929/7753803/1519ba0c-ffe8-11e4-906d-72b44cdc8938.jpg)

maybe imagemagick has not it effect, right?
i'm checked from data site http://www.imagemagick.org/Usage/backgrounds/
there is not same type "fractal"...uhmm....

**Comment by olear** [comment]
Will check, maybe SeExpr is an better alternative?

**Comment by manuelsongokuh** [comment]
i find this SeExpr...maybe a man or boy will create for natron 2?
https://twitter.com/natronvfx/status/579213513769512960

**Comment by olear** [comment]
SeExpr is already included in Natron (v2 at least) through openfx-io.

**Comment by devernay** [comment]
also check out the PlasmaCImg node

--
Frédéric Devernay, Research Scientist, INRIA
frederic.devernay@inria.fr

**Comment by manuelsongokuh** [comment]
hello devernay
few time ago i did check "plasmacimg node" that is good but not same that i did put here picture..
because fractal like as "living" or style "electricity"..
![screenshot](https://cloud.githubusercontent.com/assets/12126929/7758841/03cd3c4a-000d-11e5-83fb-f724549c8dfd.png)

ok?
maybe that https://twitter.com/natronvfx/status/579213513769512960 will be right...i'm not tested it yet..i will wait natron 2.0 hope...
okay?

**Comment by manuelsongokuh** [comment]
i did try more times for curios : plasmacimg
because evert time "re-generation" changed filter...?
(i mean from 1 frame to 30 frame always re-generation...) there is STOP?

**Comment by olear** [comment]
Seed was added to the ImageMagick API today, will start a new plugin with controllable random.

**Comment by olear** [comment]
Added a basic plugin in trunk, should fix this issue and https://github.com/MrKepzie/Natron/issues/635

Can add more features later if needed.

**Comment by manuelsongokuh** [comment]
hello
sorry if i'm back here this issue, because i find good information for programming for you..
https://en.wikipedia.org/wiki/Perlin_noise

maybe i understand, that fractal noise is from perlin noise..?
but there is code for programming:
 // Function to linearly interpolate between a0 and a1
 // Weight w should be in the range [0.0, 1.0]
 function lerp(float a0, float a1, float w) {
     return (1.0 - w)*a0 + w*a1;
 }
 
 // Computes the dot product of the distance and gradient vectors.
 function dotGridGradient(int ix, int iy, float x, float y) {
 
     // Precomputed (or otherwise) gradient vectors at each grid point X,Y
     extern float Gradient[Y][X][2];
 
     // Compute the distance vector
     float dx = x - (double)ix;
     float dy = y - (double)iy;
 
     // Compute the dot-product
     return (dx*Gradient[iy][ix][0] + dy*Gradient[iy][ix][1]);
 }
 
 // Compute Perlin noise at coordinates x, y
 function perlin(float x, float y) {
 
     // Determine grid cell coordinates
     int x0 = (x > 0.0 ? (int)x : (int)x - 1);
     int x1 = x0 + 1;
     int y0 = (y > 0.0 ? (int)y : (int)y - 1);
     int y1 = y0 + 1;
 
     // Determine interpolation weights
     // Could also use higher order polynomial/s-curve here
     float sx = x - (double)x0;
     float sy = y - (double)y0;
 
     // Interpolate between grid point gradients
     float n0, n1, ix0, ix1, value;
     n0 = dotGridGradient(x0, y0, x, y);
     n1 = dotGridGradient(x1, y0, x, y);
     ix0 = lerp(n0, n1, sx);
     n0 = dotGridGradient(x0, y1, x, y);
     n1 = dotGridGradient(x1, y1, x, y);
     ix1 = lerp(n0, n1, sx);
     value = lerp(ix0, ix1, sy);
 
     return value;
 }

this is good information for you?
:-)  :+1:

**Comment by manuelsongokuh** [comment]
other good information:
http://freespace.virgin.net/hugo.elias/models/m_perlin.htm

**Comment by manuelsongokuh** [comment]
hello, i think ... try to talk you:
is possibile create plug from SeExpr ? 
example sexpr already configured for fractal noise, and you create plug like as FRONT-END  and BACK-END from SeExpr ? and you add parameter for custom linked to changed in formule SeExpr..
this is not bad... but opinion.. it's illegal to use code?

are you understand what I'm mean?

**Comment by manuelsongokuh** [comment]
here image
![image](https://pbs.twimg.com/media/CAnHnvrWYAAj4bv.jpg:large)

**Comment by devernay** [comment]
of course, you can create a pyplug from your pre-configured seexpr, and have the useful parameters accessible (x1 in your case). You can even design your own icon for the pyplug, and put it in the right group.
Soon after the Natron 2.0 release, we will make a pyplug repository, so that users can share their plugins & pyplugs (à la Nukepedia).

**Comment by manuelsongokuh** [comment]
hello, @devernay you said "pyplug repository" will be sure?
i'm fine, but iu want not "random-generator" ok? but i'm doubt, because fractal noise needs more parameter, see screenshot:
this is default, but VERY IMPORTANT "EVOLUTION"
![schermata11](https://cloud.githubusercontent.com/assets/12126929/8487690/f4d8c52a-210d-11e5-9f3a-f89799dac5cb.png)

this is many methods of type fractal noise
![schermata12](https://cloud.githubusercontent.com/assets/12126929/8487696/fa9eba50-210d-11e5-8293-37f362a396f4.png)

there is turbulence, this is very important 
![schermata13](https://cloud.githubusercontent.com/assets/12126929/8487698/fadd46d0-210d-11e5-8061-f27c6bac2f15.png)

basic result
![basic](https://cloud.githubusercontent.com/assets/12126929/8487720/1a1f2b58-210e-11e5-856a-12c3a2e75a15.png)

dynamic-progressive result
![dynamic-progressive](https://cloud.githubusercontent.com/assets/12126929/8487722/1ab54a52-210e-11e5-88e1-995095ce5f09.png)
is seexpr does suitable..?

**Comment by manuelsongokuh** [comment]
hello,
i want to "pressure" to you, i wish to have news..? this i need more..but i did create raw fractal noisefrom AE adobe to Natron for reads file...but i want to create from natron fractal noise..

i hope ole find lamp idea  :-D

**Comment by olear** [comment]
Currently working on Natron Linux/Windows, openfx-arena won't get any new features until Natron v2 is out.

**Comment by manuelsongokuh** [comment]
hello
sorry if i'm back here, i want to tell you little news from IM forum for noise fractal:
http://www.imagemagick.org/discourse-server/viewtopic.php?f=1&t=28272&sid=a3f870f6e2dc0300cb62f227547b4fc0

please you read forum for IM, maybe (i'm not understand) can generator noise fractal..but i'm not sure..i lost something...

**Comment by olear** [comment]
Will take a look at the IM forum.
