### ISSUE TITLE
feedback for OpenFX-Arena 0.6

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#48]
hello

i did installed plug OpenFX-Arena 0.6 linux:
i'm doubt: distort from FILTER?
proposal:
OPENFX-ARENA>TRASFORM>DISTORT
OPENFX-ARENA>FILTER>EDGE

edge not adapt in distort...right o not?

**Comment by olear** [comment]
Edge is in the Distort plugin.

**Comment by olear** [comment]
I'm bundling several plugins in the distort plugin, this saves a lot of code, since most effect are just a couple of lines of code.

May move the distort plugin to 'Transfom', If it's a Filter or Transform don't matter that much too me :)

**Comment by manuelsongokuh** [comment]
hello, 
there is CRASHED in natron 2.0 with your openfx arena plug..
when i add node polar and connect from source and viewer and CRASHED..
natron 2.0 (commit d89f36eb9defc16ca11c0f427af026c54e11f1e3)

**Comment by olear** [comment]
There are problems with Natron v2 and openfx-arena.

**Comment by manuelsongokuh** [comment]
ok for natron 2.0, i'm do test competition with AE ok..

**Comment by manuelsongokuh** [comment]
i have other crash for natron 1.2.1
i add here ntp
http://www.pastefile.com/download/AzxoPm

**Comment by olear** [comment]
On Windows?

**Comment by manuelsongokuh** [comment]
not, it's LINUX for ever

**Comment by olear** [comment]
Ok, working on a new release.

Btw, works here, strange.

**Comment by manuelsongokuh** [comment]
you want to record my screen to see crash?

**Comment by olear** [comment]
Not needed.
