### ISSUE TITLE
Plugin requests

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#49]
hello

i want to show you list effect and you can see, your time will do..?
see this list effect of adobe AE:
https://helpx.adobe.com/after-effects/using/effect-list.html

**Comment by olear** [comment]
Will look into when I get the time.

**Comment by manuelsongokuh** [comment]
yes, i respect you ok?
sorry i need you help, banal, how MASK from image (white is a hole) i'm not found tutorial or documentation..y have know how does it masked (simply)?

**Comment by manuelsongokuh** [comment]
sorry again, fractal noise i did try from AE and i will send you image original from AE ok?
![sw_00001](https://cloud.githubusercontent.com/assets/12126929/7800690/846a2b9c-0319-11e5-8cbb-d6cbb1ceab56.png)

**Comment by manuelsongokuh** [comment]
for example mask from blender..for natron i'm not successful...
http://wiki.blender.org/uploads/8/85/Manual-VSE-Multiply.png

**Comment by manuelsongokuh** [comment]
i'm find information original of "cc",means: CYCORFX, it's plug in for AE default, and there are interesting information area "description", you can look that for to know and curious ok?  

http://www.cycorefx.com/popups/pluginlist.html

**Comment by manuelsongokuh** [comment]
sorry i need feedback with you..

i'm not find to understand, " hoe makes it" from cycorefx: "CC glass"
description:
"Glass can be used to give a convincing glass-like appearance to the source layer by using a user-specified bump map, displacement, light and shading properties to create a glossy, three-dimensional look. By using values from a different layer, you can create the illusion of that layer rising up through the source layer."

i dont find similar: gimp, imagemagick, other software...
bump map, displacement, uhmm not detected similar other sofwares... 
i ask you : do you have a idea, what is make it? imagemagick?

other i find INTERESTING : http://graphicdesign.stackexchange.com/questions/1803/achieving-liquid-effect-in-small-illustration

there is picture: http://i.stack.imgur.com/kdevv.jpg

i will send here other screenshot of AE adobe, for testing image effected..

a moment..

**Comment by manuelsongokuh** [comment]
i did screen record, see example "CC GLASS", i will look for for imagemagick, need free time..
link:
https://vid.me/e/cFJn

good night

**Comment by olear** [comment]
Most of your request should be possible with the GMIC plugins (when ready).
