### ISSUE TITLE
move image xy (under option ROLL) for imagemagick

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#51]
hello

i'm looking for importante move the image go right and left there is from image right...
i'm not explain good but see example picture here

this example move to top and from bottom there is from top:
![offset-example](https://cloud.githubusercontent.com/assets/12126929/7814753/7fd34464-03c4-11e5-8b36-6bcf18c21290.png)
![offset-example-wrap](https://cloud.githubusercontent.com/assets/12126929/7814752/7fcc0cb2-03c4-11e5-8fa1-21dedb11dc9b.png)

maybe it's name wrap or offset or move...?
i'm sure there is from imagemagick...

**Comment by olear** [comment]
The 'Transform' node from openfx-misc should be used to move images. Or do you mean something else?

**Comment by manuelsongokuh** [comment]
but is not move static, "move" particular, see picture
![offset-example-wrap](https://cloud.githubusercontent.com/assets/12126929/7814752/7fcc0cb2-03c4-11e5-8fa1-21dedb11dc9b.png)
there is number two color green, half body of number 2, picture from bottom there is header of two,
and top of picture there is number two but missed header, this mean when i move go to top and autamatic there is from bottom, like as game pac man: go to right and return from left..do you understand?

**Comment by manuelsongokuh** [comment]
hello

i have video screen record for explain you to move (continue) (i dont know how i can explain you)

this example from inkscape.
https://vid.me/YyEp

**Comment by manuelsongokuh** [comment]
hello
i FOUND NAME TECHNICAL "ROLL" this is from imagemagic option!!!
then see link http://www.imagemagick.org/Usage/warping/#roll

i think will be add future feature, not soon..right?

**Comment by olear** [comment]
Roll is on my TODO list, just waiting on a ImageMagick fix before I add more new stuff :)

**Comment by olear** [comment]
Added, will be part of next build.

**Comment by manuelsongokuh** [comment]
ah ok thank you, but how i can try plug in BETA?
do i  can open [git] in my computer linux and but needs to generator for binary?
i will not change code but only for testing and report bug ok?

**Comment by olear** [comment]
Snapshots: http://openfx.fxarena.net/snapshots/

If you want to build from source (build essentials needed):
```
git clone https://github.com/olear/openfx-arena
git submodule update -i
sh deploy.sh
```

Will do a proper release soon, waiting on fix in ImageMagick.

**Comment by manuelsongokuh** [comment]
ok, i will wait to finish to fix imagemagick, but i did see code source, you added Roll in distort? i think if best to separate of roll, because example:
i add roll node (distort>roll)  +  other node for poalr (distort>polar) this mean is 2 times node?
if you want keep roll in distort then okay i will do 2 node times ok? 
thank you

**Comment by olear** [comment]
Just test the snapshot, but beware that there are some issues ( #58 ).

If you want to use different effects from Distort at the same time, then you must use the Distort more times.

I can of course split distort in more plugins, but I would prefer not to do that, but it's up to the users. If enough users wants to my to split the Distort plugin, then I will do that.

**Comment by manuelsongokuh** [comment]
ah okay i respect you, that i said, is for my opinion..then all right. but natron has item "radiobox" feature?
 http://www.java2s.com/Tutorial/PythonImages/UseRadioBox.PNG

**Comment by olear** [comment]
I though about the radiobox, but I think we got too many option for that to be of any use, but can test.
