### ISSUE TITLE
Support RenderScale

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#52]
Supporting renderscale should be a high priority, the performance benefits are huge.

Must be resolved for renderscale=1:

 * Text: position and font scaling is wrong when using renderscale
 * Mirror/Distort: pixels values are wrong on zoom using renderscale

The Texture plugin should support renderscale since we don't use any coordinates or pixel values.

**Comment by manuelsongokuh** [comment]
right!

**Comment by olear** [comment]
Enabled renderscale on all plugins, only problem is with 'Text', disable renderscale in 'Text' when that works in Natron.
