### ISSUE TITLE
not work trasform (rotate) for distort 

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#54]
hello

i' did test for you:OpenFX-Arena 0.7beta1
not work trasform (rotate) with distort polare
natron is 2.0 beta (This version was generated from the source code branch workshop at commit da1dfdd1d0fa3840f28651a4af2587b7b3ef2730.)

file project natron 2.0 link:
http://www.pastefile.com/dOSH90

**Comment by olear** [comment]
What does not work? Opened you project, I see no issues.

**Comment by manuelsongokuh** [comment]
i did added key from 1 to 30 for change rotate from 0 to 360 of node trasformer but not work to rotating..

**Comment by manuelsongokuh** [comment]
did you try to PLAY to viewer?

**Comment by olear** [comment]
add crop after tranform. Not an bug in openfx-arena.

**Comment by manuelsongokuh** [comment]
ok, there is not work for rotate (trasformer) for texture (openfx-arena), this mean same not work for distort (not bug)..problem is to natron right?

**Comment by olear** [comment]
You project file works here, the transform node rotate the image as it should.
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/7838206/ea9bf878-048b-11e5-9ad4-4fccbf5282d5.png)
Note I added a crop after transform.

**Comment by manuelsongokuh** [comment]
sorry, texture with trasformer (rotate, animation key) worked but not into distort, there is screen record:
http://www.pastefile.com/ReOtb

that  your screenshot: tile is late to result but see distort not rotare and not pass to tile becuase tile is final result but for now problem is not work to rotate..see well file screen record ok?

**Comment by manuelsongokuh** [comment]
sorry again, here right screen record, sorry sigh i'm stupid..
http://www.pastefile.com/JVNolq

**Comment by olear** [comment]
When you use Transform you modify the image (the RoD will most likely be expand), the Distort plugin works as it should (it just distort what you give it, try using crop etc to limit effect area). If you want Polar with rotate I recommend using Arch with angle 360 and use the rotate option in Arc.

**Comment by manuelsongokuh** [comment]
ah ok for "If you want Polar with rotate I recommend using Arch with angle 360 and use the rotate option in Arc." so polar can not rotate right, keep calm in future can improve ok? for now first close mission for distort (polar, depolar, arc, swirl, etc) after will period you relax ok?

**Comment by manuelsongokuh** [comment]
i did try arc with rotate animation, there is strange black ...uhmm..its stange...i dont know..so i feedback to you ok?
http://www.pastefile.com/bSGQKH
