### ISSUE TITLE
Problem withTransform

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#57]
Hi olear,

Some problem with Transform:
Here a screencast:
https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-05-27_19.39.13.mkv

**Comment by olear** [comment]
Adding a crop after Transform should do it (?).

**Comment by rcspam** [comment]
Yes it solve the issu but i dont understand why ?

**Comment by olear** [comment]
The Transform node alters the RoD (region of definition), the Distort plugin just proc's what it gets, to ensure you only apply the effect to what you see you must apply a Crop.

**Comment by rcspam** [comment]
Is it a normal natron way of work or a bug in it ?

**Comment by olear** [comment]
That's normal (as far as I know).

**Comment by rcspam** [comment]
Very strange ! Thanks
