### ISSUE TITLE
Transparency issues

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#58]
There are some transparency issues in the Distort plugin. Seems to be a bug in ImageMagick 6.8 (fixed in latest version). Will do some tests.

**Comment by olear** [comment]
Confirmed fixed in ImageMagick 6.9.1. Some minor adjustments are needed (Polar alignment is wrong compared to 6.8). Will fix when I get the time tomorrow.

**Comment by olear** [comment]
Updating to 6.9.1-3 fixes Distort, but breaks Text, downgrading to 6.9.1-2 fixes both. Will find the commit that breaks and notify upstream.

For now we stop at 6.9.1-2 and use that.

**Comment by olear** [comment]
Partly fixed in ImageMagick 6.9.1-4, but that introduced another bug, waiting on feedback from the devs (they know about it, and are working on a soultion).

Next release depend on this issue.

**Comment by olear** [comment]
Binary snapshot for testing: http://openfx.fxarena.net/snapshots/Arena.ofx.bundle-0.7Beta3_Preview1-Linux-x86-release-64.tgz

**Comment by olear** [comment]
Upstream is taking it's time, I found a workaround for Text, but not the rest.

**Comment by olear** [comment]
Still no fix in sight .....

Tried changing the plugins, nothing. Tried changing composte-private in ImageMagick, but if I fix one thing I break another thing ...... The beta releases from ImageMagick does not fix anything.

**Comment by olear** [comment]
```
We reviewed the code carefully and fired upwards of 20 unit tests @ the compositing and drawing components of ImageMagick and they all return expected results. Unless you can provide a command-line or short C or C++ program we can use to reproduce the problem, we will be unable to resolve this issue.
```
And I can't give them anything to reproduce, because if I write the input/output from/to Natron to a file (in my plugin) everything is perfect (according to what I got as input)............. well; I noticed that the image I see on screen (Natron) is not the image I get from Natron, or the Image I return to Natron.

**Comment by olear** [comment]
Hmm, If I read the dstImg after I have written to it, and save that to /tmp/debug.rgba:
![screenshot-3](https://cloud.githubusercontent.com/assets/7461595/8027527/4fb23b6c-0d99-11e5-9b82-7e3419b9d221.png)
![screenshot-4](https://cloud.githubusercontent.com/assets/7461595/8027529/5c172f2a-0d99-11e5-8023-ccbf36f6912c.png)

It's perfect! WTF

```
    // return image
    if (dstClip_ && dstClip_->isConnected()) {
        switch (dstBitDepth) {
        case eBitDepthUByte:
            if (image.depth()>8)
                image.depth(8);
            image.write(0,0,width,height,"RGBA",Magick::CharPixel,(float*)dstImg->getPixelData());
            break;
        case eBitDepthUShort:
            if (image.depth()>16)
                image.depth(16);
            image.write(0,0,width,height,"RGBA",Magick::ShortPixel,(float*)dstImg->getPixelData());
            break;
        case eBitDepthFloat:
            image.write(0,0,width,height,"RGBA",Magick::FloatPixel,(float*)dstImg->getPixelData());
            break;
        }
        // debug
        Magick::Image debug;
        debug.read(width,height,"RGBA",Magick::FloatPixel,(float*)dstImg->getPixelData());
        debug.write("/tmp/debug.rgba");
    }
```

**Comment by olear** [comment]
And rendering in Natron results in perfect image:
![screenshot-5](https://cloud.githubusercontent.com/assets/7461595/8027624/4ddee626-0d9b-11e5-8b52-a8b797e5a0ca.png)

What!? Need to install Nuke and verify if this is a Natron bug or not.

**Comment by olear** [comment]
Looks like crap and renders like crap in Nuke8....

Don't understand.

**Comment by olear** [comment]
Tested Nuke9 with PNG rgba as output, get the same result as in Natron, crap in viewer, perfect when rendered. But when I render to PNG rgb it looks like crap.

**Comment by olear** [comment]
Upgrading to Natron past 31 May results in crappy rendering as well, so now what I see is what I get...

**Comment by olear** [comment]
But if I downgrade IM version then the render is perfect (not the viewer).

Epic bug!

**Comment by olear** [comment]
The only thing I can do at the moment is to work around this issue. I created a own branch for Text.ofx, that branch will remain stable and offer the Text.ofx plugin for Natron v1/v2 (will soon do a binary release).

I will remove Text.ofx from the Arena.ofx bundle, and continue to fix/workaround the other plugins in Trunk and merge with master when stuff gets more stable/predicable, The reason for the split (in bundles) is that I most likely must have more than one version of ImageMagick to support all the plugins and various kinks in ImageMagick.

**Comment by olear** [comment]
Polar status:

![screenshot](https://cloud.githubusercontent.com/assets/7461595/8050483/ec439c6c-0e6d-11e5-8a91-1d12acb00cd4.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/8050484/eece8578-0e6d-11e5-9018-4e3569c56ec5.png)

As you can see the edges are a bit jagged, but the render output from Natron:
![www](https://cloud.githubusercontent.com/assets/7461595/8050492/1111944a-0e6e-11e5-93bc-fd551418894e.png)
![www2](https://cloud.githubusercontent.com/assets/7461595/8050493/15f06306-0e6e-11e5-927c-3e64313f9abc.png)

Looks good, but if I add a merge node with an soild:
![screenshot-2](https://cloud.githubusercontent.com/assets/7461595/8050515/4da99e20-0e6e-11e5-801b-f2c2f75bc637.png)
Jagged edges, but also in render:
![www3](https://cloud.githubusercontent.com/assets/7461595/8050522/59ed299a-0e6e-11e5-8912-f85fc6f96c54.png)

**Comment by manuelsongokuh** [comment]
sorry, i want to understand, what is problem?
edge of circle color white (polar)?

**Comment by olear** [comment]
The problem is not smooth edges when input is RGBA.

And I don't know where the problem is, ImageMagick, submodules, don't know. I do know that modding the composite functions in ImageMagick give me different result, but also changing submodules....

**Comment by manuelsongokuh** [comment]
i will test this issue, but i need last snapshot of plug arena..?

**Comment by olear** [comment]
At the moment I see no point in doing a new release or snapshot, will dedicate Sunday to try to fix the issue.

**Comment by manuelsongokuh** [comment]
ok i will wait you for beta snapshot or release ok?

**Comment by olear** [comment]
Update:

Tile and Mirror works 100%, will be part of Extra.ofx, the rest will be added when they are marked stable.

Texture works, but don't support renderscale, and latest Natron v2 crashes if no renderscale.

Distort plugins and Reflection is still broken.

**Comment by manuelsongokuh** [comment]
hello

you can give me binary of plug "broken" distort and i will can see what is problem maybe i will can help you ok?

**Comment by olear** [comment]
A bit busy tonight, but will try to upload a binary. I know where the problem is, but have not found a workable solution/fix yet.

**Comment by olear** [comment]
I added a 'matte' option to the plugins affected by this issue. Workaround is to use a shuffle node or the 'matte' option in the plugin.

Been trying to fix this issue, but have not found a usable/better solution. Adding gamma to the composite-private function in IM fixes the transparency issues, but adds jagged edges, fixing the edges breaks the gamma :(

**Comment by olear** [comment]
Bug not forgotten, been testing every version of IM since "bug".

Currently latest version "works" with black background, so at least there are some progress.

**Comment by manuelsongokuh** [comment]
Good sound!
