### ISSUE TITLE
Variable blur ?

### ISSUE THREAD

**Issue by sozap** [olear/openfx-arena#60]
Hello,
I just found that ImageMagick can do variable blur mapping  :
http://www.imagemagick.org/Usage/mapping#blur
I don't know how it is complicated to implement it to your openFx suite, but that would make a very nice addition. 
It can be used to make a poor man's defocus effects, or things like a blurry vignette and so much more :)

I'm just inceptioning the idea so you can unleash the magick !!

**Comment by olear** [comment]
I'm busy with work until Sunday, but can look at blurring after that (need to fix a couple of bugs first)

**Comment by sozap** [comment]
Awesome , thanks !!

**Comment by olear** [comment]
I recommend asking for blur enhancements in openfx-misc, creating a dedicated blur plugin with IM has been done before and the result was not the best (performance).
