### ISSUE TITLE
Text: add support for src clip

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#61]
Why Text.ofx doesn't take account node in its 'Source input' to merge it under text. 
Will we must always use a Merge node or is it a future improve ?

**Comment by olear** [comment]
Text is a generator not an effect/filter, this will not change.

**Comment by rcspam** [comment]
Olear,
Sorry for my  ignorance about OFX development, but to have a similar use with other text plugins, is it possible to code it with a "merge over" B input as source input or is it is not a correct way to do ?

**Comment by rcspam** [comment]
So i had constructed a Python plugins based on Merge node and your Magick Text node to have a source background (Merge + Text). The problem is the spot position doesn't appear on viewer. So have you an explanation ? Is this due to Natron or OpenFxArena... or me ?
[Here](https://dl.dropboxusercontent.com/u/2677320/TextB.py) is the Python plugin

**Comment by olear** [comment]
Hi, just got home from a long work weekend, will look into your problem a bit later today.

**Comment by olear** [comment]
I put your script in the plugin folder, and got this:
![screenshot-2](https://cloud.githubusercontent.com/assets/7461595/7901784/9ba00fd6-079a-11e5-9e13-065f5514174e.png)

I have no experience with Python in Natron :) (yet)

**Comment by olear** [comment]
My bad (a bit tired yet), some plugins was missing on my installation, will retest.

**Comment by olear** [comment]
I guess this is what you get:
![screenshot-3](https://cloud.githubusercontent.com/assets/7461595/7901829/c54db0fc-079c-11e5-8e7f-53be2bde19aa.png)

As said earlier, I don't known how Python in Natron works, so can't help you on this one (the Text plugin works, so not an issue in openfx-arena as far as I know).

**Comment by rcspam** [comment]
I have create the plugin simply with the gui from node tab of the group (Input - Merge - Text - Output). I have never do that before, I just found all this out. There are some display bug but it s really cool...

**Comment by olear** [comment]
Ok, will do some test and see if I can find out where the issue comes from.

**Comment by olear** [comment]
If all you want is a bg color, then I can add support for that in the Text plugin?

**Comment by rcspam** [comment]
I want just  the source input for background like other text plugins (Nuke, buggy natron text...).
So operations menu and mix slider could be a good feature, but if you can add a color background too, 
that's even better ;)
The good thing for me is that i have learn to create a python plugin:
![espace de travail 1_001](https://cloud.githubusercontent.com/assets/10021906/7903314/139cf7aa-07d8-11e5-90f6-9714e16379c6.png)

**Comment by olear** [comment]
Added background color support, note that TextOIIO is a Filter not a Generator. Text as a generator is more flexible than as a Filter.

**Comment by rcspam** [comment]
Cool ! Do you think 'Bg source input' is impossible to code because this is not a filter but a generator ?

**Comment by olear** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/7461595/7903455/478f7b00-07dd-11e5-8c62-bc70267a3ee9.png)

Added initial support for src clip, but found a small bug in imagemagick that needs to be fixed before I merge the changes.

**Comment by rcspam** [comment]
Argh! Unlucky Text! Waiting! 
Thanks.

**Comment by olear** [comment]
I'm currently unable to find the error in ImageMagick, srcClip feature may be delayed (v0.8), same for issue #53

**Comment by rcspam** [comment]
In the meantime, we can use the python plugin....

**Comment by olear** [comment]
Yeah, sorry about that. But I need to wait on feedback from the ImageMagick devs.

**Comment by rcspam** [comment]
What ImageMagick library is use ?

**Comment by olear** [comment]
6.9.1-2, but they are all broken.

**Comment by olear** [comment]
Got some feedback from upstream, they say that the problem should be fixed in next release or the next after that one, will follow SVN and backport if needed.

**Comment by olear** [comment]
Getting worse with latest ImageMagick release .........

![screenshot](https://cloud.githubusercontent.com/assets/7461595/7923864/e9d384f4-08b6-11e5-9313-95f2a7a880d6.png)
![screenshot-1](https://cloud.githubusercontent.com/assets/7461595/7923865/e9d4ee5c-08b6-11e5-9529-84c6a47fae56.png)

**Comment by olear** [comment]
feature added in new branch, will merge and add before next beta release.

**Comment by rcspam** [comment]
I can remove my python plugin :)
Thanx

**Comment by olear** [comment]
Note that next beta has been delayed due to issues with ImageMagick :(

**Comment by rcspam** [comment]
The impatience is not a issue ;)

**Comment by olear** [comment]
Had to revert the addition of src clip and background color due to issue #58. Will re-add as soon as that issue has been resolved.

**Comment by rcspam** [comment]
As i can see [here](http://www.imagemagick.org/discourse-server/viewtopic.php?f=23&t=27732&sid=3426b1709dfe171bc0797d757099aea9&start=15), the IM devs has been somewhat expectant of late. (?_?)

**Comment by olear** [comment]
Yeah, that bug report is going nowhere, so I must find a fix myself :(

**Comment by rcspam** [comment]
Good luck !
