### ISSUE TITLE
Texture: add more generators

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#70]
i think need more new filter easy to create code for you, (maybe i'm wrong to think)

new filter/texture A:
start:
![flare_1aa](https://cloud.githubusercontent.com/assets/12126929/8005301/cf25f4c8-0b88-11e5-8c12-3783fc4d80bb.png)
command
convert -size 500x1 xc: +noise Random -channel G -separate +channel A-CREATE.png

![noise-random](https://cloud.githubusercontent.com/assets/12126929/8005258/35785bfe-0b88-11e5-9f23-7945aef4929c.png)
command
convert -size 500x1 xc: +noise Random -channel G -separate +channel -scale 500x500\! A-RESULT.png

new filter/texture B:
![star_fall](https://cloud.githubusercontent.com/assets/12126929/8005458/94c28330-0b8a-11e5-85a0-03e5a82061fd.png)
command
convert -size 500x500 xc: +noise Random -channel R -threshold .4% -negate -channel RG -separate +channel +clone -flatten -virtual-pixel tile -blur 0x.4 -motion-blur 0x20+45 -normalize RESULT-B.png

come from: http://www.imagemagick.org/Usage/advanced/
![star_fall](https://cloud.githubusercontent.com/assets/12126929/8005503/1d6e48cc-0b8b-11e5-9f65-cce60d29fc51.png)

command:
convert -size 500x500 xc: +noise Random -channel R -threshold .4% -negate -channel RG -separate +channel +clone  -compose multiply -flatten -virtual-pixel tile -blur 0x.4 -motion-blur 0x20+45 -normalize star_fall.png

new filter/texture C:
(family gradient 1)
![gradient_cosine](https://cloud.githubusercontent.com/assets/12126929/8005607/4fbc2f3c-0b8c-11e5-8dbf-e06a112161ff.jpg)
command
convert -size 500x500 gradient: -evaluate cos 0.5 -negate gradient1.png

(family gradient 2)
![gradient_peak](https://cloud.githubusercontent.com/assets/12126929/8005718/6e66b802-0b8d-11e5-8ce5-8525cadd45c9.png)
command
convert -size 500x500 gradient: -function Polynomial -4,4,0 gradient2.png

(family gradient 3)
![gradient_bands](https://cloud.githubusercontent.com/assets/12126929/8005745/b451d220-0b8d-11e5-878c-7f36c28c91c7.jpg)
command
convert -size 500x500 gradient: -function sinusoid 4,-90   gradient3.jpg

(family gradient 4)
![oo](https://cloud.githubusercontent.com/assets/12126929/8006017/1c55bc9a-0b90-11e5-8748-573e0b968432.png)
command
convert -size 100x100 radial-gradient: gradient4.png
link: http://www.imagemagick.org/Usage/canvas/#radial-gradient
change colours :
![rgradient_range3](https://cloud.githubusercontent.com/assets/12126929/8006058/7cee873a-0b90-11e5-8bd4-3172920ed8a9.jpg)

(family gradient 5)
![gradient_venetian](https://cloud.githubusercontent.com/assets/12126929/8006093/d3bd34c6-0b90-11e5-983c-2740cac6736d.jpg)
command 
convert -size 500x500 gradient: +clone +clone -background gray50 -compose ModulusAdd -flatten gradient5.png

(family gradient 6)
![gradient_rainbow_2](https://cloud.githubusercontent.com/assets/12126929/8006399/c6035970-0b93-11e5-80eb-9a4540cec910.jpg)
command
convert -size 600x600 gradient:'#FFF-#0FF' -rotate 90 -set colorspace HSB -colorspace RGB gradient6.png

(family gradient 7)
![gradient_rs_rainbow](https://cloud.githubusercontent.com/assets/12126929/8006443/36672084-0b94-11e5-92a9-30096d28fe0e.jpg)
command
convert xc:black xc:red xc:yellow xc:green1 xc:cyan xc:blue xc:black +append -filter Cubic -resize 600x600\! gradient7.png

(family gradient 8)
![gradient_transparent](https://cloud.githubusercontent.com/assets/12126929/8007042/254dc640-0b99-11e5-9bb4-3401a2cf1bbe.png)
command
convert -size 500x500 gradient:none-firebrick gradient_transparent.png

i'm finish this issue care, remember it's not for soon to create, this is for future (ROADMAP), this is memo note ok?

**Comment by olear** [comment]
Texture B and "star fall" is too slow, would be better to use nodes from Natron on a noise background to replicate the background?

**Comment by manuelsongokuh** [comment]
for now "star fall" is suspended, because it's not important, but important "base" of gradients that all gradients are very important for compositor natron under your plug ok?

**Comment by olear** [comment]
![screenshot-4](https://cloud.githubusercontent.com/assets/7461595/8172173/4ae619ac-13be-11e5-80ae-fa8747c8a0cd.png)

Ramp and Radial not enough?

**Comment by manuelsongokuh** [comment]
i know natron have gradient and radial but i'm not sure if your plug is same result?

for this reason imagemagick is powerfully, like as TEXT (openfx) and your TEXT (imagemagick) here is result workd diverse...

so need to test it..

example gradient "family gradient 3" there are more gradients but without use : tiles+crop+trasform..right or not?

**Comment by olear** [comment]
Ok, will add :)

**Comment by manuelsongokuh** [comment]
ok...i need to find better engine and stable for natron from your code ok?

sorry i need last snapshot code...is there ?

**Comment by olear** [comment]
working snapshots of Natron should be located at http://sourceforge.net/projects/natron/files/snapshots/linux64/repo/

If not I can upload what I use.

**Comment by manuelsongokuh** [comment]
sorry i mean your plug last snapshot...or you mean your plug is merged to natron?

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/releases/tag/0.7Beta4

**Comment by olear** [comment]
Can't get Polynomial  and the other distort technique to work in Magick++

Will add if I get that working.
