### ISSUE TITLE
new filter: "Fast Gaussian Blur"

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#71]
HI
i find and very necessary "blur" but MAX FAST
find command and script:
http://www.fmwconcepts.com/imagemagick/tidbits/image.php#fast_gblur

is for future..

**Comment by devernay** [comment]
hmmm... it will probably not be faster than https://github.com/devernay/openfx-misc 's Blur, which has always the same speed, whatever the kernel size is (and is much more "Gaussian" than Nuke's blur, which applies the technique you point to)
I wouldn't spend time on coding that one

**Comment by olear** [comment]
Blur in ImageMagick out-of-the-box is not the fastest, can be enhanced with OpenCL and with tweak etc, but as @devernay says not point in recreating what already works.
