### ISSUE TITLE
Text plugin: add a letter spacing

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#72]
Hi olear,
Is it possible to add a letter spacing parameter (i.e. TuttleText Node) in the text plugin?
Regards

**Comment by olear** [comment]
Not an option at the moment, I know ImageMagick supports Pango but have not tested it yet.

**Comment by olear** [comment]
Found http://www.imagemagick.org/Usage/text/#kerning Will check if this works with Magick++, if so will add.

**Comment by olear** [comment]
Done, will be part of next release.

**Comment by rcspam** [comment]
Cool !
