### ISSUE TITLE
openfx-arena without Text

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#77]
Hi Olear,
Can you put in line a openfx-arena version without Text plugin.
If we install both, arenaText takes over.
Good job, i re-discover the power of IM to produce image from text in my own bash script :)
Thanx

**Comment by rcspam** [comment]
.... Pehaps a separate version of pango Text to test it.
A little bug here if pango is not set in 0.4 text:
![screenshot1](https://cloud.githubusercontent.com/assets/10021906/8101120/6fec9cf6-1014-11e5-96ea-86835898b8ad.png)

**Comment by rcspam** [comment]
.... Little bug in "word spacing": the spacing start about 80, so when we set right over 0 (between 0 & 80), the space jump right away....

**Comment by olear** [comment]
pango can't be enable until a rebuild of Natron due to conflict with Cairo. Will produce a Linux version of Natron that supports Pango by the end of this weekend. When Pango is enabled you will have a "Pango Markup" checkbox in the GUI.

will check word spacing.

**Comment by rcspam** [comment]
I understand, but as i show in the screenshot, pango being not set in this version, if we put some markup in the text box, it disappears in it and the text display right in the viewer. I suppose a little bug when switching between Pango - Not Pango

**Comment by olear** [comment]
Noticed that the some text disappears if you use <markup>foo</markup>, the text field is controlled by the host as far as I know, and has nothing with the plugin, will check.

**Comment by rcspam** [comment]
Ok, will wait ! Thanx

**Comment by olear** [comment]
regarding word space.

0.0>0.4 = no word space, default spacing
0.5 = null word space, no spacing
0.6> or <0.0= some word space

Will check if this can be changed (in IM).

**Comment by olear** [comment]
new build soon
