### ISSUE TITLE
About Shadow text

### ISSUE THREAD

**Issue by rcspam** [olear/openfx-arena#79]
The shadow offset is only limited to 10 (if a valor  >10 is set, the shadows became increasingly blur ).
A more precise shadows could be improve with more parameters: blur (in x and/or y), offset  (in x and/or y), and color (this can act as transparency as well).

As explain [here](http://imagemagick.org/Usage/fonts/#fuzzy)
If i do this in command line:
```
shadow_color='#000000ff';x=15;y=65;of=-10;bx=10;by=10
convert -size 350x80  xc:white \
 -pointsize 72 -fill ${shadow_color} -annotate +${x}+${y} 'Shadow' \
 -blur ${bx}x${by} -fill blue -annotate +$((${x}+${of}))+$((${y}+${of})) 'Shadow' \
 Shadow_test.png
```
I know i am very boring ;)
But what do you think?

**Comment by olear** [comment]
Will test and fix if possible.

**Comment by rcspam** [comment]
I dont know if all this above improve can be done in Magick++...
But we can add this one: To avoid the text move and only move the shadow when we change offset, just instead of add offset to text, we can subtract it from shadow:
```
convert -size 350x80  xc:white \
 -pointsize 72 -fill ${shadow_color} -annotate +$((${x}-${of}))+$((${y}-${of})) 'Shadow' \
 -blur ${bx}x${by} -fill blue -annotate +${x}+${y} 'Shadow' \
 Shadow_test.png
```
So the text stay in place we put it, only the shadow move.
I hope it's possible.

**Comment by olear** [comment]
Will try, been busy with work these last days.

Todo:
- Fix offset over 10
- move shadow not text

More?

**Comment by rcspam** [comment]
Yes offset in x and y

**Comment by olear** [comment]
will add x/y a bit later today

**Comment by olear** [comment]
Done, fixes and enhancements will be part of next release (will tag and upload binaries later today).

Please reopen this issue if I did something wrong etc :)

**Comment by rcspam** [comment]
Hi Olear,
Thank you for the enhancement work.
Can i say some things...

1. About gui:
  * *Color controllers must be with their parameters groups because it's more natural, i think.*
  * *Is Shadow_Offset controllers be Double2DParam type to win a line ?*
  * *Is Shadow_Opacity can be set with a color RGBAParam type to win a line ? (i'm not sure if it's    possible !)*

2. About Shadow/Stroke:
  * *If we want have a simple blur under the text without offset, it's impossible, turn up Shadow sigma systematically  increase offset to SouthEast although with Offsets to zero.*
  * *A little bug display: a tiny stroke line stay although with Shadow and Sroke off (see the screeshot)*

![screenshot2](https://cloud.githubusercontent.com/assets/10021906/8147987/5f6c7652-1286-11e5-8866-777335c9f1b5.png)

I hope you understand what i mean because my English is not so good...
Regards

**Comment by rcspam** [comment]
I forgot, can you put Inline a brundle without Text...
thanx

**Comment by olear** [comment]
1.1:
I'm not sure, I prefer the the params as-is, but that's probably a matter of taste.

1.2:
May change

2.1:
Then use merge+blur ;) , It's a simple dropshadow effect, can look into alternative methods. I'm using the shadow effect from ImageMagick, that's how it works, if not, then I must do it manually (no problem).

2.2:
Will check, but may not be fixable (only option may be to drop background color)

**Comment by rcspam** [comment]
I have test with command line and [-blur](http://www.imagemagick.org/script/command-line-options.php?#blur) parameter (radiusXsigma) and it works well....

**Comment by olear** [comment]
I know blur works, as I said I use the 'shadow' function in IM:
```
shadow
	const double percent_opacity = 80, const double sigma_ = 0.5, const ssize_t x_ = 0, const ssize_t y_ = 0 	simulate an image shadow
```

I must rewrite the shadow function to use blur instead, will do some tests later today.

**Comment by rcspam** [comment]
Sorry !!! Hard days ?? ;)

**Comment by olear** [comment]
2.2: bgcolor

I can workaround if no shadow, but if I use shadow then I hit issue #58 

I don't know.... remove bgcolor?

**Comment by rcspam** [comment]
Yes remove bg . Easy to add a merge node or to construct a python-plugin...
