### ISSUE TITLE
Texture: renderscale

### ISSUE THREAD

**Issue by olear** [olear/openfx-arena#84]
it's not possible to support renderscale in this plugin, disable if this works in Natron.

**Comment by olear** [comment]
Renderscale=0 equals crash in latest Natron2.

**Comment by olear** [comment]
Hmm, removed everything that's related to renderscale, but still get "renderscale behaviour"..

**Comment by olear** [comment]
Got it working on Natron1, but segfaults on Natron2.

**Comment by olear** [comment]
also tried flipping renderscale based on pango boolean in Text, work kind-of, the text is ok on 50ish % and higher, but lower it's blank, on both Natron1 and Natron2.

**Comment by olear** [comment]
disabled renderscale in trunk, still an issue

**Comment by manuelsongokuh** [comment]
hello maybe this is resolve for renderscale, see link
https://github.com/MrKepzie/Natron/commit/446924897c75e7a911399a8d553e9d0b27c40809

**Comment by olear** [comment]
I know :)

https://github.com/MrKepzie/Natron/issues/567#issuecomment-116019970
