### ISSUE TITLE
MotionBlur on various plugins

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#87]
hello

ROLL: is MAGIC!!! try move x or y is very COOL but MAGNIFICENT TERRIBLE!!!
THIS IS MISSION GOLD!! YOU HAVE GOOD JOB!! COMPLIMENT!! 

  
if you wish to improve?
-add feather (bolder and blur..depend what is best way..) black or white or color or alpha, this is option..
-maybe cool: motion blur like as effect "glitch" (smooth) this is could be COOL...uhmm..
this motion blur link roll not trasformer (natron)..this is not bad if add parameter...its can will late...need to thinkig.. ok?

so REST to say ROLL IS MAGNIFICENT!

**Comment by manuelsongokuh** [comment]
POLAR/DEPOLAR:
IS TRUE MAGNIFICENT! COMPLIMENT!! I'M WONDERFUL OF YOU!
SURE ALL PEOPLE (NUKE, FUSION,) WILL BE SURPRISE FULL!

if you wish to improve?
-enhancement SNAP in parameter 3 to 5 pixel under mouse snap each unit:
-360 | -315 | -270 | -225 | -180 | -135 | -90 | -45 |  0  | +45 | +90 | +135 | +180 | +225 | +270 | +315 | +360

-add feather (bolder and blur..depend what is best way..) black or white or color or alpha, this is option..
-motion blur : moviment from rotate from high speed  until slow speed, this is could be COOL..

all of rest: depend from you time free and you think is want or move next milestone (for me is not problem, because you did done realized: ROLL and POLAR and ARC etc it's very GOLD..
for now you go to relax!!
good nite

**Comment by manuelsongokuh** [comment]
i add here file for you, 
for now i do testing again time,
this video used from your plug:
ROLL, POLAR, also plug of natron:
merge, read,roto, grade,costaint.
BUT IF YOUR PLUG IS NOT REALIZED SO I NEVER DO IT!

video link:
http://www.pastefile.com/EtsEui
(need click "download" because html5 player not work, because it's file mov ok?)

for now it's testing and demo, when i will finish my testing and i will do true tutorial and public under TO USE YOUR PLUG ok?

for "enhancement"
[motionblur for rotate > polar]
[motionblur for x,y > ROLL]
[snap slider (high-snap) > polar,arc,swirl, etc
i will wish testing it, not as soon, not as shock, not as stress code, ok?

**Comment by olear** [comment]
Can test motion blur on roll etc, but can't guarantee anything ;)

**Comment by olear** [comment]
added motionblur to Roll but the performance is not good, the only option is to enable OpenCL, or use blur from openfx-misc.

**Comment by manuelsongokuh** [comment]
ok, thank for your testing and resulted, i will test blur of openfx-misc ok?
thank you again..

**Comment by olear** [comment]
I can of course add it, but the performance will not be great... :(
