### ISSUE TITLE
Text: clone or copy or linked..(dont know name yet)

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#88]
text is grow up and stable..

but very necessary: feature for text: copy text 'content'..
i dont know what is name technical, you can choose good look for name ok?

see my propostal, it's not hard, it's maybe easy for you (it's your funny code) 
see pciture for first:
![g3357](https://cloud.githubusercontent.com/assets/12126929/8173777/c3a208a6-13d2-11e5-9844-9f5208bde7bd.png)

second:
![g3365](https://cloud.githubusercontent.com/assets/12126929/8173787/fb7ac3b2-13d2-11e5-91d7-d56f1188b4d0.png)

third:
![g4272](https://cloud.githubusercontent.com/assets/12126929/8173869/7ea2f86c-13d4-11e5-9e30-0317c037cdb7.png)

**Comment by olear** [comment]
![screenshot-5](https://cloud.githubusercontent.com/assets/7461595/8174586/b34e9968-13de-11e5-89c7-ca126fd93bc4.png)
![screenshot-6](https://cloud.githubusercontent.com/assets/7461595/8174589/b82e81c8-13de-11e5-966e-4a3629c08468.png)

Use Python in Natron.

Right-click on text field (on copy/clone/whatever), select edit expression, then type: Text1.text.get();

**Comment by manuelsongokuh** [comment]
hello,
that is FINE for python but people or new user does not know about "clone/copy", how they will know if wanted copy/clone?

"Text1.text.get()" is hard to remember (it is not easy to remember or people did not wont to remember ... this is defect..)

do you have an idea for best solution? 

now i'm remember AE adobe has similar tecnhical: "parents" like as copy/clone.. use with mouse drag (line) until to target object...

one theory:
IF you add "copy or clone" like as my propostal:
![g3357](https://cloud.githubusercontent.com/assets/12126929/8173777/c3a208a6-13d2-11e5-9844-9f5208bde7bd.png)
 this means people will readed "copy" or "clone" and will understand that is clone or copy so people will can think for to use it..

this is theory only, and you are free to choose new code or rest to use python expression ok?

**Comment by manuelsongokuh** [comment]
i'm forget add link for AE adobe example powerfully parenting, you can see and you will feel like as vary ATTRACT...
https://www.youtube.com/watch?v=omYO1jRgaC8

**Comment by olear** [comment]
one possibility is to use a shared text file, this is possible with the pango features in the plugin, but the python stuff will be easier, if you enable pango then you must use a markup language to style the text.

The feature you want must be handled by the host, that means python or use a clone etc.

**Comment by manuelsongokuh** [comment]
ok, that is fine for your thought.
see result for clone/copy powerfully.. 
but when i start to play viewer is very slow..i think:
POSSIBILE once time render out for text and stop in cache and not re-render group of text..?

![schermata3](https://cloud.githubusercontent.com/assets/12126929/8192326/a1ba131e-146d-11e5-9f4e-1a156a50fed8.png)

**Comment by manuelsongokuh** [comment]
i want to know:
unit of stroke text, what is based of width?
px or pt?
px is most usage software: photo editing, Word processor, video editing, compositor..
instead "width" is nor clear.. what is used unit of?

**Comment by olear** [comment]
the Natron2 performance is not good (I get more or less same performance on my laptop 2 threads vs workstation 12 threads), something wrong with the threading (I guess). openfx-arena uses the threads given by host, more cores equal better performance.

**Comment by olear** [comment]
Does it matter? :) probably pt I guess.

**Comment by manuelsongokuh** [comment]
ok, that is question, 
for professional information, UI, words, icons, colors UI, etc..
PT is correct information and that WIDTH is other thing, width is general information..this is my thought, if you want remain word WIDTH so you choose, the plug is yours ok?




other information pt / width max number: 10pt with mouse slider?
(i know i can put in number freedom but slider is blocked to 10pt,it's normal?

**Comment by olear** [comment]
10 max can be changed, I used a sane default, can't be too high, then the slider will be to hard to use. Will bump the slider max on next release.
