### ISSUE TITLE
Text: alternative stroke

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#89]
hello 

see example picture:
![ids_strokestyles_001](https://cloud.githubusercontent.com/assets/12126929/8173970/3bba4e86-13d6-11e5-91a2-49993dcc59cc.png)

colud be few style: dot circle, double lines,  dot square, that is sufficient.

it's possible or hard to code..?

see an example "base" and CUTE result:
(but not SAME but similar ok?)
![pic-13](https://cloud.githubusercontent.com/assets/12126929/8173990/a54ec912-13d6-11e5-8c26-0526a556483e.png)

other example:
![borderstyles](https://cloud.githubusercontent.com/assets/12126929/8174027/5d55be08-13d7-11e5-9779-7cacdce380ba.png)

**Comment by olear** [comment]
Feature not available in ImageMagick, but will try to add something similar.

**Comment by olear** [comment]
Unable to add this request in Text without major code change, some options are possible in TextPango.

**Comment by manuelsongokuh** [comment]
ok, let me as know for this particular stroke outliner style in pango, you are believe 100% port in pango like as stable or reliable?
good night

**Comment by olear** [comment]
Need to do some tests, but think pango supports alternative strokes. TextPango is feature complete.

**Comment by manuelsongokuh** [comment]
ok, i want to know who is Pango..get me a link? i'm curious to know it :-)

**Comment by olear** [comment]
https://github.com/olear/openfx-arena/wiki/Pango

**Comment by olear** [comment]
May have found the possibility to add dashed outline, will add if works

**Comment by olear** [comment]
Got something working:
![screenshot-8](https://cloud.githubusercontent.com/assets/7461595/8392000/40947988-1cda-11e5-99cb-53ac91cd2cc2.png)

Getting there :P

**Comment by olear** [comment]
unable to modify stroke without the path line .... need to ask IM devs.

**Comment by manuelsongokuh** [comment]
ok better to ask IM devs..
thank you

**Comment by olear** [comment]
http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=19319

Will be added when/if fixed in IM.

**Comment by olear** [comment]
http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=19319&p=125360#p125357

Not supported/broken, don't expect this to change (I don't know enough about IM to fix this).

**Comment by manuelsongokuh** [comment]
ok, thank you for time for look for resolve.. but failed, i hope for future will does fix.. when will fix IM for text stroke special then back here to re-open...:-) 
then thank you for used your time for this issue ok?
thank you

**Comment by olear** [comment]
I will of course add the feature as soon as it's available in IM :)

**Comment by manuelsongokuh** [comment]
there are new news for this bug?

**Comment by olear** [comment]
TextFX (new text node) supports dashed strokes.

**Comment by manuelsongokuh** [comment]
HI
i wish to ask you there are other style of stroke than dashed?
this functional: where are it from code based (IM)?

**Comment by manuelsongokuh** [comment]
hi there a news from IM forum http://www.imagemagick.org/discourse-server/viewtopic.php?f=3&t=19319&p=140900#p140900
