### ISSUE TITLE
Radial Blur: have nt it, right?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#91]
natron has not "radial blur"..
but imagemagick there is "radial blur" (http://www.fmwconcepts.com/imagemagick/polarblur/index.php)
parameter:
-Center: X, Y  (for position of origin radial)
-range (or amount or seed or other name) number from 0 to 100, (100 is out of viewer) 
this is for "Arguments: -r 10 -a 0"  "radial blur" of fred's imageimagic.

this is sufficient 2 parameter.
better single plug for effect ok?

but i'm not capable test command in bash ...
i wish to test first from command terminal...

**Comment by manuelsongokuh** [comment]
sorry of disturbance..
you did try command imagemagick under terminal? becuase i need to try and check image result..
i'm idiot.. I can not find the correct commands...

do you try it under terminal?

**Comment by olear** [comment]
See issue #60 

Will look into a blur-like plugin in v0.8.

**Comment by devernay** [comment]
Natron definitely has a radial blur, and my guess is that it may be better than IM's...
It's called DirBlur.

**Comment by olear** [comment]
Blur functions in IM has bad performance, and if it exists in Natron I will not add it.

**Comment by manuelsongokuh** [comment]
DirBlur, i have strange full CPU..
when i add dirblur and set SCALA:12, blocked for full cpu, i cant KILL process..KILL FORCE, killed natron..
file ntp
http://www.pastefile.com/V1HqFU

**Comment by devernay** [comment]
congratulations, you found a bug! (even better: two bugs - one in Natron and one in the plugins)

**Comment by devernay** [comment]
Bugs fixed in Natron.
Note that dirblur is geometrically correct (and really corresponds to scaling the image), whereas the script you are pointing to gives a wrong result.
You can get the same effect as that script by chaining ToPolar->Blur in 1 direction (x or y)->ToRectangular
This can easily be done in a pyplug

**Comment by manuelsongokuh** [comment]
hello
i wanted to try radial blur, i try with dirblur use with scala..
this i wanted to against AE adobe like as competitor, so want natron have same level for feature.
AE has radial blur so i ask alear if can add radial blur under imagemagic, instead devernay said there is "dirblur" so i start to try it and i find strange full CPU and blocked..
then i waiting for fix it the bug and  will try competitor AE..

example alear create plug magnific: ROLL, POLAR, for natron so can competitor AE..
i wanted to be natron best and better for open source..
ok?
:-)

**Comment by manuelsongokuh** [comment]
plug polar of arena has major of AE:
flip, rotate, AE have not flip and rotate this is WINNER natron/arena!!!
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by manuelsongokuh** [comment]
@devernay i  did sent you email private, please go to read ok?
@olear i did send him for testing effect of blur radial (dirblur) maybe not use ridial blur of imagemagick for moment..ok?
