### ISSUE TITLE
Text: stroke can addition ?

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#95]
hello

need to addition more stroke over stroke over..
see link imagemagic:
http://www.imagemagick.org/Usage/fonts/#psychedelic
command:

---
convert -size 320x100 xc:lightblue -font Candice -pointsize 72 -fill white \
           -stroke black -strokewidth 25 -annotate +25+65 'Anthony' \
           -stroke white -strokewidth 20 -annotate +25+65 'Anthony' \
           -stroke black -strokewidth 15 -annotate +25+65 'Anthony' \
           -stroke white -strokewidth 10 -annotate +25+65 'Anthony' \
           -stroke black -strokewidth  5 -annotate +25+65 'Anthony' \
           -stroke none                  -annotate +25+65 'Anthony' \
           font_psychedelic.jpg

---
 need add button for ADD NEW STROKE (same that default of text arena: width, color.)
this is good?
![Alt Text]
(http://www.imagemagick.org/Usage/fonts/font_psychedelic.jpg)

**Comment by olear** [comment]
That command just makes several copies of the text and adds variable strokes, just do the same in Natron(?).

**Comment by manuelsongokuh** [comment]
ok, it's same if i add more node text? if yes that fine.
if not same then will need fix text plug?

**Comment by manuelsongokuh** [comment]
sorry i'm back here again because i have feedback for you ok?
i'm try try and test test test test..
result:

when i add many node of text, text, text (using clone/copy) for multiplier result WORKED but true problem:
WHEN I MOVE TEXT (POSITION X,Y) i need changed X,Y each all node text.. this mean i lose a lot time..
IF IF IF you add stroke1,stroke2,stroke3,stroke4,stroke5,stroke6,stroke7,stroke8,stroke9,stroke10 
THIS MEAN I SAVE A LOT A LOT TIME for change position X,Y like as realt-time..

this is my report test, testing for your plug text..and you are freedom of choose for FIX IT or NOT FIX IT ok?

![schermata7](https://cloud.githubusercontent.com/assets/12126929/8232778/84feff3a-15d2-11e5-9b9a-4051969004c7.png)
my case 6 stroke and i move text (x,y) a lot time to change each them..

**Comment by sozap** [comment]
you can put a transform node after you mix all the texts, or maybe link the positions with expressions...

**Comment by manuelsongokuh** [comment]
hello sozap
for ADD trasform node needs ADD CROP node this mean 2 node added, so will slow render..
if text added many stroke in one so 1 unique:

1 PLUG TEXT-ARENA vs MANY NODE (text+text+text+text+text>>>merge+trasform+crop)
this is right?
for this reason i tell this report for understand "there is stress" ok?

**Comment by manuelsongokuh** [comment]
for many stroke it's not good TOO, TOO nodes...
TEXT-ARENA is very BEST than natron text, for more stroke in one plug and not nodes..
i did try more time and i'm nod satisfaction : 

MANY NODE (natron+arena) (text+text+text+text+text>>>merge+trasform+crop)
:-1:  :-1: :-1:  :-1: :-1:  :-1: :-1:  :-1: 



1 PLUG TEXT-ARENA "SINGLE" (10 strokes,shadows,font,spacing,text,cloned/copy)
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by olear** [comment]
![screenshot-2](https://cloud.githubusercontent.com/assets/7461595/8243308/48c70226-1616-11e5-9e49-2b2ef15258f7.png)

Don't get any slowdown... And you will most likely end up with many nodes in all projects, that gives you more flexibility.

Adding diskcace node and/or using canvas size in the Text plugin may help on performance.

I'm on a old Intel Core2 2.4Ghz laptop and have no performance issues with Text.

**Comment by manuelsongokuh** [comment]
ok for slowdown.
you have 3 node of text: TARGET more stroke right?
this mean you FORCED TO USE 2 NODE "MERGE" (if 3 stroke)

then you try create video for text: 10 STROKE = jobs a lot for time right?

y try imagine if you add code for 10 stroke and you will create ONE node text there are many feature option, so 1 node text= time SAVED A LOT..

i suggest you better to add code because one time create plug, it's FOREVER BEST PLUG
because AE have not it "ONE NODE" because AE have used many many layer layer for TEXT target many STROKE..

**Comment by manuelsongokuh** [comment]
![image10-8](https://cloud.githubusercontent.com/assets/12126929/8252166/4e633368-1683-11e5-86a0-505abca848c6.png)
this is example to show you for think.. ok?
:)

**Comment by manuelsongokuh** [comment]
see example AE:
many LAYER for text (for MANY STROKE)
![image10](https://cloud.githubusercontent.com/assets/12126929/8258311/2eae0b66-16b4-11e5-9013-44f1a7b4626c.png)
