### ISSUE TITLE
Text: add stroke cap/join

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#96]
hello
MISSED!
see example of inkscape:
![schermata4](https://cloud.githubusercontent.com/assets/12126929/8213794/d5057bca-1524-11e5-849c-d53397a1ded7.png)
because when the letter T there is square and text-arena result "round"..

this is text arena plug natron
![schermata5](https://cloud.githubusercontent.com/assets/12126929/8213890/adbd47a4-1525-11e5-89b9-682b59c6d7a0.png)

this is text inkscape
![schermata6](https://cloud.githubusercontent.com/assets/12126929/8213907/c1b38b6a-1525-11e5-9bfb-a642c9ce1af0.png)

**Comment by olear** [comment]
Text.ofx will never be as good as a dedicated "Text" program, that requires writing the plugin from scratch, that's not something I'm planning at the moment, or in the future (there must be a really good reason for me to even think about starting from scratch). The plugin uses ImageMagick and is bound by that (I can only do stuff that's supported in ImageMagick), it's possible to use the Pango features (advanced users) to fix some of the "missing" features from the plugin, but that also has it's shortcomings.

My mission with the Text.ofx plugin was to make it as-good or better than the alternatives (Nuke Text/TextOIIO/TuttleText), and currently I think it is.

**Comment by manuelsongokuh** [comment]
OF COURSE!!!
did you asked them for ADD feature?

**Comment by olear** [comment]
Will ask.

**Comment by olear** [comment]
ImageMagick has support for stroke cap/join, but when added they don't do anything, don't know if it's a bug or not a feature when using text.

**Comment by manuelsongokuh** [comment]
you can try to ask or write topic official forum imagemagick...ok?

**Comment by olear** [comment]
Will contact them.

**Comment by olear** [comment]
hmm, squarecap works when I tested dashed stroke:

No line cap:
![screenshot-9](https://cloud.githubusercontent.com/assets/7461595/8392021/d296df7e-1cda-11e5-813d-fbb9c16a442e.png)

Square line cap:
![screenshot-10](https://cloud.githubusercontent.com/assets/7461595/8392022/d9035fe0-1cda-11e5-9494-0f606896cddf.png)

**Comment by manuelsongokuh** [comment]
it's resolved?
thank you..

**Comment by olear** [comment]
Kind of, code has been added to the plugin, but works best with custom stroke (not added).
