### ISSUE TITLE
Text: support font style/weight/stretch

### ISSUE THREAD

**Issue by manuelsongokuh** [olear/openfx-arena#98]
hello

i'm start to use force TEXT for TESTING TESTING

i detected to missed..
NORMAL,BOLD,ITALICS,UNDERLINE..are missed from text Arena...

i hope next milestone new features ok?

**Comment by olear** [comment]
bold and italic are in the font menu/list. underline has been removed, but can be added through pango (advanced).

**Comment by olear** [comment]
Btw, underline etc was removed since it wasn't adjustable (size/color), can make a bug/feature report at ImageMagick and hope they fix/add it.

**Comment by manuelsongokuh** [comment]
ok, of course for report at imagemagick..
i hope they will fix/add it
:-)

**Comment by manuelsongokuh** [comment]
it's resolved?

**Comment by olear** [comment]
See font family list, no point in adding additional params.
